# 🏏 IPL 2024 - Complete Pandas Practice Notebook
### 275 Questions across 11 Sections | Basic → Advanced
---
**Dataset**: IPL 2024 Batting Stats  
**Columns**: POS, Player, Runs, Mat, Inns, NO, HS, Avg, BF, SR, 100, 50, 4s, 6s  
**Total Players**: 167

---

## ⚙️ Setup - Run This First

In [2]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('IPL_Status_2024.csv')
print('Dataset loaded successfully!')
print(f'Shape: {df.shape}')
df.head()

Dataset loaded successfully!
Shape: (167, 14)

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113*,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108*,53.00,413,141.16,1,4,58,18
2,3,Riyan Parag RR,573,16,14,3,84*,52.09,384,149.21,0,4,40,33
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24

---
# 📥 Section 1: Data Loading & Saving (25 Questions)
---

### Q1. [Basic] Load the IPL_Status_2024.csv file into a DataFrame called `df`

In [3]:
df = pd.read_csv('IPL_Status_2024.csv')
df.head()

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113*,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108*,53.00,413,141.16,1,4,58,18
2,3,Riyan Parag RR,573,16,14,3,84*,52.09,384,149.21,0,4,40,33
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24

### Q2. [Basic] Display the first 5 rows of the DataFrame

In [4]:
df.head()

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113*,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108*,53.00,413,141.16,1,4,58,18
2,3,Riyan Parag RR,573,16,14,3,84*,52.09,384,149.21,0,4,40,33
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24

### Q3. [Basic] Display the last 3 rows of the DataFrame

In [5]:
df.tail(3)

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
164,165,Manav Suthar GT,1,1,1,0,1,1.0,2,50.00,0,0,0,0
165,166,Vyshak Vijaykumar RCB,1,4,2,1,1*,1.0,3,33.33,0,0,0,0
166,167,Ishant Sharma DC,1,9,2,2,1*,0.0,7,14.28,0,0,0,0

### Q4. [Basic] Load only the first 50 rows of the CSV file

In [6]:
df1 = pd.read_csv('IPL_Status_2024.csv',nrows=50)

### Q5. [Basic] Load only the columns: 'Player', 'Runs', 'Mat', 'SR'

In [7]:
df2 = pd.read_csv('IPL_Status_2024.csv',usecols=['Player','Runs','Mat','SR'])
df2

                    Player  Runs  Mat      SR
0          Virat Kohli RCB   741   15  154.69
1      Ruturaj Gaikwad CSK   583   14  141.16
2           Riyan Parag RR   573   16  149.21
3          Travis Head SRH   567   15  191.55
4          Sanju Samson RR   531   16  153.46
..                     ...   ...  ...     ...
162     Lizaad Williams DC     1    2   50.00
163      Keshav Maharaj RR     1    2   50.00
164        Manav Suthar GT     1    1   50.00
165  Vyshak Vijaykumar RCB     1    4   33.33
166       Ishant Sharma DC     1    9   14.28

[167 rows x 4 columns]

### Q6. [Basic] Save the DataFrame to a new file called 'ipl_backup.csv' without the index

In [8]:
df2.to_csv('Updated_ipl',index=False)

### Q7. [Basic] Save only the top 10 players (by POS) to 'top10.csv'

In [9]:
top_10 = df.head(10)
top_10.to_csv('top10.csv')

### Q8. [Basic] Create a DataFrame manually with 3 players: Kohli (741 runs), Gaikwad (583 runs), Parag (573 runs)

In [10]:
three = pd.DataFrame([
    {
        'Player':'Virat Kohli',
        'Runs': 741
    },
    {
        'Player': 'Gaikwad',
        'Runs': 583
    },
    {
        'Player': 'Parag',
        'Runs' : 573     
    }
])
three

        Player  Runs
0  Virat Kohli   741
1      Gaikwad   583
2        Parag   573

### Q9. [Basic] Load the CSV and skip the first 10 rows

In [11]:
skip = pd.read_csv('IPL_Status_2024.csv',skiprows=10)
skip

,10,Abhishek Sharma SRH,484,16,16.1,1,75*,32.27,237,204.21,0,3,36,42
0,11,Heinrich Klaasen SRH,479,16,15,3,80*,39.92,280,171.07,0,4,19,38
1,12,Rishabh Pant DC,446,13,13,2,88*,40.55,287,155.40,0,3,36,25
2,13,Faf Du Plessis RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21
3,14,Phil Salt KKR,435,12,12,1,89*,39.55,239,182.00,0,4,50,24
4,15,Yashasvi Jaiswal RR,435,16,15,1,104*,31.07,279,155.91,1,1,54,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,163,Lizaad Williams DC,1,2,1,1,1*,0.00,2,50.00,0,0,0,0
153,164,Keshav Maharaj RR,1,2,1,0,1,1.00,2,50.00,0,0,0,0
154,165,Manav Suthar GT,1,1,1,0,1,1.00,2,50.00,0,0,0,0
155,166,Vyshak Vijaykumar RCB,1,4,2,1,1*,1.00,3,33.33,0,0,0,0
156,167,Ishant Sharma DC,1,9,2,2,1*,0.00,7,14.28,0,0,0,0

### Q10. [Basic] Check how many rows and columns the CSV has without loading the full file

In [12]:
# Load with nrows=0 to just get columns, then use wc-l style approach
colu = pd.read_csv('IPL_Status_2024.csv',nrows=0)
print('column:',len(colu.columns))

with open('IPL_Status_2024.csv', 'r') as f:
    num_rows = sum(1 for _ in f) - 1  # subtract header

print("Rows:", num_rows)

column: 14
Rows: 167

### Q11. [Intermediate] Load the CSV file and set 'Player' column as the index

In [13]:
# Hint: use index_col parameter
df3 = pd.read_csv('IPL_Status_2024.csv',index_col='Player')
df3

,POS,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
Player,,,,,,,,,,,,,
Virat Kohli RCB,1,741,15,15,3,113*,61.75,479,154.69,1,5,62,38
Ruturaj Gaikwad CSK,2,583,14,14,3,108*,53.00,413,141.16,1,4,58,18
Riyan Parag RR,3,573,16,14,3,84*,52.09,384,149.21,0,4,40,33
Travis Head SRH,4,567,15,15,1,102,40.50,296,191.55,1,4,64,32
Sanju Samson RR,5,531,16,15,4,86,48.27,346,153.46,0,5,48,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Lizaad Williams DC,163,1,2,1,1,1*,0.00,2,50.00,0,0,0,0
Keshav Maharaj RR,164,1,2,1,0,1,1.00,2,50.00,0,0,0,0
Manav Suthar GT,165,1,1,1,0,1,1.00,2,50.00,0,0,0,0
Vyshak Vijaykumar RCB,166,1,4,2,1,1*,1.00,3,33.33,0,0,0,0
Ishant Sharma DC,167,1,9,2,2,1*,0.00,7,14.28,0,0,0,0

### Q12. [Intermediate] Save the top 20 players to a JSON file called 'top20.json'

In [14]:
top20 = df.head(20)
top20.to_json('top20.json')

### Q13. [Intermediate] Load the CSV and rename columns while loading: 'Runs' → 'Total_Runs', 'Mat' → 'Matches'

In [15]:
# Hint: load first, then rename
df = pd.read_csv('IPL_Status_2024.csv')
df = df.rename(columns={
    'Runs': 'Total_Runs',
    'Mat': 'Matches'
})
df

,POS,Player,Total_Runs,Matches,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113*,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108*,53.00,413,141.16,1,4,58,18
2,3,Riyan Parag RR,573,16,14,3,84*,52.09,384,149.21,0,4,40,33
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,Lizaad Williams DC,1,2,1,1,1*,0.00,2,50.00,0,0,0,0
163,164,Keshav Maharaj RR,1,2,1,0,1,1.00,2,50.00,0,0,0,0
164,165,Manav Suthar GT,1,1,1,0,1,1.00,2,50.00,0,0,0,0
165,166,Vyshak Vijaykumar RCB,1,4,2,1,1*,1.00,3,33.33,0,0,0,0
166,167,Ishant Sharma DC,1,9,2,2,1*,0.00,7,14.28,0,0,0,0

### Q14. [Intermediate] Load the CSV with 'POS' as index and verify using df.index

In [16]:
# Your code here
df = pd.read_csv('IPL_Status_2024.csv',index_col='POS')
df.index

RangeIndex(start=1, stop=168, step=1, name='POS')

### Q15. [Intermediate] Save the DataFrame to CSV with only these columns: Player, Runs, SR, Avg

In [17]:
# Hint: use columns parameter in to_csv()
df.to_csv(
    'ipl_filtered.csv',
    columns=['Player', 'Runs', 'SR', 'Avg'],
    index=False
)

### Q16. [Intermediate] Create a DataFrame from a list of dictionaries for 5 players with their stats

In [18]:
data = [
    {'Player': 'Virat Kohli', 'Runs': 741, 'SR': 154.69, 'Avg': 61.75},
    {'Player': 'Rohit Sharma', 'Runs': 417, 'SR': 150.00, 'Avg': 32.08},
    {'Player': 'MS Dhoni', 'Runs': 161, 'SR': 220.55, 'Avg': 53.67},
    {'Player': 'KL Rahul', 'Runs': 520, 'SR': 136.48, 'Avg': 37.14},
    {'Player': 'Shubman Gill', 'Runs': 426, 'SR': 147.40, 'Avg': 38.72}
]

df = pd.DataFrame(data)

print(df)

         Player  Runs      SR    Avg
0   Virat Kohli   741  154.69  61.75
1  Rohit Sharma   417  150.00  32.08
2      MS Dhoni   161  220.55  53.67
3      KL Rahul   520  136.48  37.14
4  Shubman Gill   426  147.40  38.72

### Q17. [Intermediate] Load CSV, then export only players with Runs > 300 to 'high_scorers.csv'

In [19]:
df = pd.read_csv('IPL_Status_2024.csv')
high = df[df['Runs']>300]
high.to_csv('high_scorers.csv')

### Q18. [Intermediate] Read the CSV in chunks of 20 rows and print the shape of each chunk

In [20]:
# Hint: use chunksize parameter
for chunk in pd.read_csv('IPL_Status_2024.csv', chunksize=20):
    print(chunk.shape)

(20, 14)
(20, 14)
(20, 14)
(20, 14)
(20, 14)
(20, 14)
(20, 14)
(20, 14)
(7, 14)

### Q19. [Advanced] Load CSV, convert to JSON with orient='records' and print the first record

In [21]:
import json

df = pd.read_csv('IPL_Status_2024.csv')

json_data = df.to_json(orient='records')

records = json.loads(json_data)

print(records[0])

{'POS': 1, 'Player': 'Virat Kohli RCB', 'Runs': 741, 'Mat': 15, 'Inns': 15, 'NO': 3, 'HS': '113*', 'Avg': 61.75, 'BF': 479, 'SR': 154.69, '100': 1, '50': 5, '4s': 62, '6s': 38}

### Q20. [Advanced] Load the CSV twice and concatenate them into one DataFrame, then drop duplicates

In [22]:
df1 = pd.read_csv('IPL_Status_2024.csv')
df2 = pd.read_csv('IPL_Status_2024.csv')
combined = pd.concat([df1, df2], ignore_index=True)
combined=combined.drop_duplicates()
combined.shape

(167, 14)

### Q21. [Advanced] Load CSV with custom dtype: Runs as float32, Mat as int8 to save memory

In [23]:
# Hint: use dtype parameter
df = pd.read_csv('IPL_Status_2024.csv',dtype={'Runs':np.float32,'Mat':np.int8})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   POS     167 non-null    int64
 1   Player  167 non-null    str
 2   Runs    167 non-null    float32
 3   Mat     167 non-null    int8
 4   Inns    167 non-null    int64
 5   NO      167 non-null    int64
 6   HS      167 non-null    str
 7   Avg     167 non-null    float64
 8   BF      167 non-null    int64
 9   SR      167 non-null    float64
 10  100     167 non-null    int64
 11  50      167 non-null    int64
 12  4s      167 non-null    int64
 13  6s      167 non-null    int64
dtypes: float32(1), float64(2), int64(8), int8(1), str(2)
memory usage: 16.6 KB

### Q22. [Advanced] Create a multi-level column DataFrame with player batting and fielding stats

In [24]:
# Hint: use pd.MultiIndex.from_tuples for columns
data = {

    ('Batting', 'Runs'): [741, 417, 520],

    ('Batting', 'SR'): [154.69, 150.00, 136.48],

    ('Fielding', 'Catches'): [12, 8, 10]

}

df = pd.DataFrame(

    data,

    index=['Virat Kohli', 'Rohit Sharma', 'KL Rahul']

)
df

             Batting         Fielding
                Runs      SR  Catches
Virat Kohli      741  154.69       12
Rohit Sharma     417  150.00        8
KL Rahul         520  136.48       10

### Q23. [Advanced] Save DataFrame to CSV with tab separator instead of comma

In [25]:
# Hint: use sep parameter in to_csv()
df.to_csv('IPL.csv',sep='-')

### Q24. [Advanced] Load CSV and parse the 'Player' column to extract Team name (last word) during load

In [26]:
# Note: Player column has format 'Name TEAM' e.g. 'Virat Kohli RCB'
# Your code here
df = pd.read_csv('IPL_Status_2024.csv')
df['Team'] = df['Player'].str.extract(r'(\w+)$')

### Q25. [Advanced] Use pd.read_csv with converters to auto-clean the HS column (remove '*' during load)

In [27]:
# Hint: use converters={'HS': lambda x: str(x).replace('*', '')}
import pandas as pd

df = pd.read_csv(
    'IPL_Status_2024.csv',
    converters={
        'HS': lambda x: x.replace('*', '')
    }
)

print(df['HS'].head())

0    113
1    108
2     84
3    102
4     86
Name: HS, dtype: str

---
# 🔍 Section 2: Exploratory Data Analysis - EDA (25 Questions)
---

### Q1. [Basic] Print the shape (rows, columns) of the DataFrame

In [28]:
# Your code here
df.shape

(167, 14)

### Q2. [Basic] Print all column names

In [29]:
# Your code here
df.columns

Index(['POS', 'Player', 'Runs', 'Mat', 'Inns', 'NO', 'HS', 'Avg', 'BF', 'SR',
       '100', '50', '4s', '6s'],
      dtype='str')

### Q3. [Basic] Check data types of all columns

In [30]:
# Your code here
df.dtypes

POS         int64
Player        str
Runs        int64
Mat         int64
Inns        int64
NO          int64
HS            str
Avg       float64
BF          int64
SR        float64
100         int64
50          int64
4s          int64
6s          int64
dtype: object

### Q4. [Basic] Get summary statistics for all numeric columns

In [31]:
# Your code here
df.describe()

,POS,Runs,Mat,Inns,NO,Avg,BF,SR,100,50,4s,6s
count,167.00000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000
mean,84.00000,147.658683,8.982036,6.736527,1.461078,19.794611,98.029940,129.349641,0.083832,0.766467,13.017964,7.544910
std,48.35287,167.073780,4.955796,4.751922,1.652849,15.126400,105.155675,46.616890,0.298857,1.298498,15.488228,9.609049
min,1.00000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,14.280000,0.000000,0.000000,0.000000,0.000000
25%,42.50000,12.500000,4.000000,2.000000,0.000000,4.835000,13.500000,100.000000,0.000000,0.000000,1.000000,0.000000
50%,84.00000,69.000000,10.000000,5.000000,1.000000,19.000000,54.000000,135.480000,0.000000,0.000000,7.000000,3.000000
75%,125.50000,235.000000,14.000000,11.000000,2.000000,30.450000,168.500000,155.655000,0.000000,1.000000,21.500000,12.000000
max,167.00000,741.000000,16.000000,16.000000,8.000000,62.380000,479.000000,300.000000,2.000000,5.000000,64.000000,42.000000

### Q5. [Basic] Get detailed info about the DataFrame (dtypes, nulls, memory)

In [32]:
# Your code here
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   POS     167 non-null    int64
 1   Player  167 non-null    str
 2   Runs    167 non-null    int64
 3   Mat     167 non-null    int64
 4   Inns    167 non-null    int64
 5   NO      167 non-null    int64
 6   HS      167 non-null    str
 7   Avg     167 non-null    float64
 8   BF      167 non-null    int64
 9   SR      167 non-null    float64
 10  100     167 non-null    int64
 11  50      167 non-null    int64
 12  4s      167 non-null    int64
 13  6s      167 non-null    int64
dtypes: float64(2), int64(10), str(2)
memory usage: 18.4 KB

### Q6. [Basic] Count unique values in the 'Player' column

In [33]:
# Your code here
df['Player'].nunique()

167

### Q7. [Basic] Find the player with the maximum runs

In [34]:
# Your code here
df.loc[df['Runs'].idxmax()]

POS                     1
Player    Virat Kohli RCB
Runs                  741
Mat                    15
Inns                   15
NO                      3
HS                    113
Avg                 61.75
BF                    479
SR                 154.69
100                     1
50                      5
4s                     62
6s                     38
Name: 0, dtype: object

### Q8. [Basic] Find the minimum Strike Rate (SR) in the dataset

In [35]:
# Your code here
df.loc[df['SR'].idxmin()]

POS                    167
Player    Ishant Sharma DC
Runs                     1
Mat                      9
Inns                     2
NO                       2
HS                       1
Avg                    0.0
BF                       7
SR                   14.28
100                      0
50                       0
4s                       0
6s                       0
Name: 166, dtype: object

### Q9. [Basic] Get a random sample of 5 players from the dataset

In [36]:
# Your code here
df.sample(5,random_state=42)

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
101,102,Karn Sharma RCB,31,9,3,0,20,10.33,15,206.66,0,0,2,3
108,109,Bhuvneshwar Kumar SRH,23,16,5,2,13,7.67,29,79.31,0,0,3,0
78,79,Anuj Rawat RCB,98,5,5,1,48,24.50,77,127.27,0,0,10,3
56,57,Shai Hope DC,183,9,9,1,41,22.88,122,150.00,0,0,12,12
98,99,Swapnil Singh RCB,37,7,5,3,15,18.50,21,176.19,0,0,3,3

### Q10. [Basic] Count how many players scored at least one century (100 > 0)

In [37]:
# Your code here
(df['Runs']>=100).value_counts()

Runs
False    89
True     78
Name: count, dtype: int64

### Q11. [Intermediate] Find the average runs scored across all players

In [38]:
# Your code here
print(df['Runs'].mean().round(2))

147.66

### Q12. [Intermediate] Count unique values per column using nunique()

In [39]:
# Your code here
x = df.columns
for y in x:
    print(df[y].nunique())

167
167
114
16
16
8
80
123
106
135
3
6
46
32

### Q13. [Intermediate] Find how many players have played more than 10 matches

In [40]:
# Your code here
print((df['Mat'] > 10).sum())

75

### Q14. [Intermediate] Display the distribution of 6s column using value_counts()

In [41]:
# Your code here
df6 = df['6s'].value_counts()
df6.head()

6s
0    48
1    17
2    15
5     7
3     7
Name: count, dtype: int64

### Q15. [Intermediate] Find the median batting average (Avg) across all players

In [42]:
# Your code here
print(df['Avg'].median())

19.0

### Q16. [Intermediate] Find the top 5 players by Strike Rate (SR)

In [43]:
# Your code here
df.sort_values('SR',ascending=False).head()

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
131,132,Luke Wood MI,9,2,1,1,9,0.00,3,300.00,0,0,0,1
88,89,Romario Shepherd MI,57,6,5,3,39,28.50,21,271.42,0,0,5,5
28,29,Jake Fraser - McGurk DC,330,9,9,0,84,36.67,141,234.04,0,4,32,28
62,63,MS Dhoni CSK,161,14,11,8,37,53.67,73,220.54,0,0,14,13
123,124,Sai Kishore GT,13,5,2,1,13,13.00,6,216.66,0,0,0,2

### Q17. [Intermediate] Get memory usage of the DataFrame

In [44]:
# Hint: df.memory_usage(deep=True)
df.memory_usage(deep=True)

Index       132
POS        1336
Player    11007
Runs       1336
Mat        1336
Inns       1336
NO         1336
HS         8486
Avg        1336
BF         1336
SR         1336
100        1336
50         1336
4s         1336
6s         1336
dtype: int64

### Q18. [Intermediate] Show the 25th and 75th percentile of Runs column

In [45]:
# Hint: use describe() or quantile()
df['Runs'].quantile([0.25,0.75])

0.25     12.5
0.75    235.0
Name: Runs, dtype: float64

### Q19. [Intermediate] Find which player has the highest batting average (Avg) with at least 10 innings

In [46]:
# Your code here
inning = df[df['Inns']>=10]
inning.loc[inning['Avg'].idxmax()]

POS                         8
Player    Nicholas Pooran LSG
Runs                      499
Mat                        14
Inns                       14
NO                          6
HS                         75
Avg                     62.38
BF                        280
SR                     178.21
100                         0
50                          3
4s                         35
6s                         36
Name: 7, dtype: object

### Q20. [Intermediate] Get frequency distribution of number of 50s scored

In [47]:
# Your code here
df['50'].value_counts()

50
0    110
1     22
2     14
4      9
3      9
5      3
Name: count, dtype: int64

### Q21. [Advanced] Find the IQR (Interquartile Range) of the Runs column

In [48]:
# IQR = Q3 - Q1

q1 = df['Runs'].quantile(0.25)
q3 = df['Runs'].quantile(0.75)

iqr = q3 - q1
print(iqr)

222.5

### Q22. [Advanced] Calculate coefficient of variation (std/mean * 100) for SR column

In [49]:
# Your code here
cov = ((df['SR'].std())/(df['SR'].mean()))*100
print(cov.round(2))

36.04

### Q23. [Advanced] Find the skewness and kurtosis of the Runs column

In [50]:
# Hint: df['Runs'].skew(), df['Runs'].kurt()
df['Runs'].skew()
df['Runs'].kurt()

np.float64(0.4809313956424215)

### Q24. [Advanced] Create a summary table showing min, max, mean, std for Runs, SR, and Avg together

In [51]:
# Hint: use .agg() on multiple columns
df[['Runs','SR','Avg']].agg(['max','min','mean','median'])

              Runs          SR        Avg
max     741.000000  300.000000  62.380000
min       1.000000   14.280000   0.000000
mean    147.658683  129.349641  19.794611
median   69.000000  135.480000  19.000000

### Q25. [Advanced] Find outliers in the Runs column using IQR method (beyond 1.5*IQR from Q1/Q3)

In [52]:
# Your code here
q1 = df['Runs'].quantile(0.25)
q3 = df['Runs'].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

outliers = df[(df['Runs'] < lower_bound) | (df['Runs'] > upper_bound)]

print(outliers)

   POS               Player  Runs  Mat  Inns  NO   HS    Avg   BF      SR  \
0    1      Virat Kohli RCB   741   15    15   3  113  61.75  479  154.69
1    2  Ruturaj Gaikwad CSK   583   14    14   3  108  53.00  413  141.16
2    3       Riyan Parag RR   573   16    14   3   84  52.09  384  149.21

   100  50  4s  6s
0    1   5  62  38
1    1   4  58  18
2    0   4  40  33

---
# 🧹 Section 3: Handling Missing Values (25 Questions)
---

### Q1. [Basic] Check if there are any null values in the DataFrame

In [53]:
# Your code here
df.isnull().values.any()

np.False_

### Q2. [Basic] Count the number of null values in each column

In [54]:
# Your code here
df.isnull().sum()

POS       0
Player    0
Runs      0
Mat       0
Inns      0
NO        0
HS        0
Avg       0
BF        0
SR        0
100       0
50        0
4s        0
6s        0
dtype: int64

### Q3. [Basic] Introduce null values: set Runs to NaN for players ranked below 100

In [55]:
df_copy = df.copy()
df_copy.loc[df_copy['POS'] > 100, 'Runs'] = np.nan
print(df_copy['Runs'].isnull().sum())

67

### Q4. [Basic] Drop all rows where Runs is NaN (using df_copy from above)

In [56]:
# Your code here
df_copy = df_copy.dropna(subset=['Runs'])
df_copy

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741.0,15,15,3,113,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad CSK,583.0,14,14,3,108,53.00,413,141.16,1,4,58,18
2,3,Riyan Parag RR,573.0,16,14,3,84,52.09,384,149.21,0,4,40,33
3,4,Travis Head SRH,567.0,15,15,1,102,40.50,296,191.55,1,4,64,32
4,5,Sanju Samson RR,531.0,16,15,4,86,48.27,346,153.46,0,5,48,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Azmatullah Omarzai GT,42.0,7,4,0,17,10.50,33,127.27,0,0,2,2
96,97,Nitish Rana KKR,42.0,2,2,0,33,21.00,34,123.52,0,0,5,1
97,98,Devdutt Padikkal LSG,38.0,7,7,0,13,5.43,53,71.69,0,0,3,0
98,99,Swapnil Singh RCB,37.0,7,5,3,15,18.50,21,176.19,0,0,3,3
99,100,Mohammad Nabi MI,35.0,7,5,1,23,8.75,31,112.90,0,0,2,2

### Q5. [Basic] Fill NaN values in Runs column with 0

In [57]:
# Your code here using df_copy
df_copy['Runs']= df_copy['Runs'].fillna(0)

### Q6. [Basic] Fill NaN values in Runs column with the mean of Runs

In [58]:
# Your code here using df_copy
df_copy['Runs']=df_copy['Runs'].fillna(df_copy['Runs'].mean())

### Q7. [Basic] Fill NaN values in Runs column with the median of Runs

In [59]:
# Your code here using df_copy
df_copy['Runs']=df_copy['Runs'].fillna(df_copy['Runs'].median())

### Q8. [Basic] Find percentage of missing values per column

In [60]:
# Hint: (df.isnull().sum() / len(df)) * 100
(df.isnull().sum()/len(df))*100

POS       0.0
Player    0.0
Runs      0.0
Mat       0.0
Inns      0.0
NO        0.0
HS        0.0
Avg       0.0
BF        0.0
SR        0.0
100       0.0
50        0.0
4s        0.0
6s        0.0
dtype: float64

### Q9. [Basic] Show all rows where at least one column has a NaN (use df_copy)

In [61]:
# Hint: df[df.isnull().any(axis=1)]
df_copy[df_copy.isnull().any(axis=1)]

Empty DataFrame
Columns: [POS, Player, Runs, Mat, Inns, NO, HS, Avg, BF, SR, 100, 50, 4s, 6s]
Index: []

### Q10. [Basic] Drop columns that have more than 50% missing values

In [62]:
# Hint: use thresh parameter in dropna()
df_copy = df_copy.drop(
    columns=df_copy.columns[(df_copy.isnull().sum() / len(df_copy)) * 100 > 50]
)

### Q11. [Intermediate] Create df_missing with NaN in SR for players with Runs < 50, then forward-fill the NaNs

In [63]:
df_missing = df.copy()
df_missing.loc[df_missing['Runs'] < 50, 'SR'] = np.nan
# Forward fill
df_missing.fillna('NaNs')

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,Lizaad Williams DC,1,2,1,1,1,0.00,2,NaNs,0,0,0,0
163,164,Keshav Maharaj RR,1,2,1,0,1,1.00,2,NaNs,0,0,0,0
164,165,Manav Suthar GT,1,1,1,0,1,1.00,2,NaNs,0,0,0,0
165,166,Vyshak Vijaykumar RCB,1,4,2,1,1,1.00,3,NaNs,0,0,0,0
166,167,Ishant Sharma DC,1,9,2,2,1,0.00,7,NaNs,0,0,0,0

### Q12. [Intermediate] Backward-fill NaN values in SR column

In [64]:
# Your code here using df_missing
df_missing["SR"] = df_missing["SR"].bfill()
df_missing

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,Lizaad Williams DC,1,2,1,1,1,0.00,2,NaN,0,0,0,0
163,164,Keshav Maharaj RR,1,2,1,0,1,1.00,2,NaN,0,0,0,0
164,165,Manav Suthar GT,1,1,1,0,1,1.00,2,NaN,0,0,0,0
165,166,Vyshak Vijaykumar RCB,1,4,2,1,1,1.00,3,NaN,0,0,0,0
166,167,Ishant Sharma DC,1,9,2,2,1,0.00,7,NaN,0,0,0,0

### Q13. [Intermediate] Use interpolate() to fill missing SR values

In [65]:
# Your code here using df_missing
df_copy["SR"] = df_copy["SR"].interpolate()

### Q14. [Intermediate] Replace NaN in Runs with the mode of Runs column

In [66]:
# Hint: df['Runs'].mode()[0]

### Q15. [Intermediate] Check which players have both Runs and SR missing

In [67]:
# Your code here

### Q16. [Intermediate] Fill missing values with different strategies per column: Runs→mean, SR→median, Avg→0

In [68]:
# Hint: use fillna with a dict

### Q17. [Intermediate] Count total missing values in the entire DataFrame

In [69]:
# Your code here

### Q18. [Intermediate] Drop rows only if both Runs AND SR are NaN simultaneously

In [70]:
# Hint: use subset and how='all' in dropna()

### Q19. [Advanced] Detect and fill missing values using a custom function based on batting average

In [71]:
# Fill missing Runs = Avg * (Inns - NO) when Runs is NaN

### Q20. [Advanced] Create a heatmap-style boolean mask showing where nulls are

In [72]:
# df.isnull() gives boolean DataFrame
# Print columns with their null counts side by side

### Q21. [Advanced] Use KNN-like logic: fill missing SR by the average SR of 5 nearest players by Runs

In [73]:
# Simplified approach using sort and rolling

### Q22. [Advanced] Fill NaN Runs with interpolation method='polynomial' order=2

In [74]:
# Your code here

### Q23. [Advanced] After filling NaN, verify no nulls remain using assert

In [75]:
# assert df_filled.isnull().sum().sum() == 0

### Q24. [Advanced] Build a missing value report: column name, count, %, recommend fill strategy

In [76]:
# Your code here

### Q25. [Advanced] Replace 0 values in 100s and 50s columns with NaN (treat 0 as missing), then fill with mode

In [77]:
# Hint: df.replace(0, np.nan)

---
# ✂️ Section 4: Selecting & Filtering Data (25 Questions)
---

### Q1. [Basic] Select only the 'Player' column

In [78]:
# Your code here
df['Player']

0            Virat Kohli RCB
1        Ruturaj Gaikwad CSK
2             Riyan Parag RR
3            Travis Head SRH
4            Sanju Samson RR
               ...
162       Lizaad Williams DC
163        Keshav Maharaj RR
164          Manav Suthar GT
165    Vyshak Vijaykumar RCB
166         Ishant Sharma DC
Name: Player, Length: 167, dtype: str

### Q2. [Basic] Select columns: 'Player', 'Runs', 'SR'

In [79]:
# Your code here
df[['Player','Runs','SR']]

                    Player  Runs      SR
0          Virat Kohli RCB   741  154.69
1      Ruturaj Gaikwad CSK   583  141.16
2           Riyan Parag RR   573  149.21
3          Travis Head SRH   567  191.55
4          Sanju Samson RR   531  153.46
..                     ...   ...     ...
162     Lizaad Williams DC     1   50.00
163      Keshav Maharaj RR     1   50.00
164        Manav Suthar GT     1   50.00
165  Vyshak Vijaykumar RCB     1   33.33
166       Ishant Sharma DC     1   14.28

[167 rows x 3 columns]

### Q3. [Basic] Get the 10th row using iloc

In [80]:
# Your code here
df.iloc[9]

POS                        10
Player    Abhishek Sharma SRH
Runs                      484
Mat                        16
Inns                       16
NO                          1
HS                         75
Avg                     32.27
BF                        237
SR                     204.21
100                         0
50                          3
4s                         36
6s                         42
Name: 9, dtype: object

### Q4. [Basic] Get rows 0 to 4 using iloc

In [81]:
# Your code here
df.iloc[0:4]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32

### Q5. [Basic] Filter players who scored more than 400 runs

In [82]:
# Your code here
df.loc[df['Runs']>400]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24
5,6,Sai Sudharsan GT,527,12,12,1,103,47.91,373,141.28,1,2,48,16
6,7,K L Rahul LSG,520,14,14,0,82,37.14,382,136.12,0,4,45,19
7,8,Nicholas Pooran LSG,499,14,14,6,75,62.38,280,178.21,0,3,35,36
8,9,Sunil Narine KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33
9,10,Abhishek Sharma SRH,484,16,16,1,75,32.27,237,204.21,0,3,36,42
10,11,Heinrich Klaasen SRH,479,16,15,3,80,39.92,280,171.07,0,4,19,38
11,12,Rishabh Pant DC,446,13,13,2,88,40.55,287,155.40,0,3,36,25
12,13,Faf Du Plessis RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21
13,14,Phil Salt KKR,435,12,12,1,89,39.55,239,182.00,0,4,50,24
14,15,Yashasvi Jaiswal RR,435,16,15,1,104,31.07,279,155.91,1,1,54,16
15,16,Shubman Gill GT,426,12,12,1,104,38.73,289,147.40,1,2,37,15
16,17,Rohit Sharma MI,417,14,14,1,105,32.08,278,150.00,1,1,45,23
17,18,Tilak Varma MI,416,13,13,3,65,41.60,278,149.64,0,3,35,19

### Q6. [Basic] Filter players who hit more than 30 sixes

In [83]:
# Your code here
df[df['6s']>30]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
7,8,Nicholas Pooran LSG,499,14,14,6,75,62.38,280,178.21,0,3,35,36
8,9,Sunil Narine KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33
9,10,Abhishek Sharma SRH,484,16,16,1,75,32.27,237,204.21,0,3,36,42
10,11,Heinrich Klaasen SRH,479,16,15,3,80,39.92,280,171.07,0,4,19,38
19,20,Rajat Patidar RCB,395,15,13,0,55,30.38,223,177.13,0,5,21,33

### Q7. [Basic] Filter players with Strike Rate > 150

In [84]:
# Your code here
df[df['SR']>150]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24
7,8,Nicholas Pooran LSG,499,14,14,6,75,62.38,280,178.21,0,3,35,36
8,9,Sunil Narine KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33
9,10,Abhishek Sharma SRH,484,16,16,1,75,32.27,237,204.21,0,3,36,42
10,11,Heinrich Klaasen SRH,479,16,15,3,80,39.92,280,171.07,0,4,19,38
11,12,Rishabh Pant DC,446,13,13,2,88,40.55,287,155.40,0,3,36,25
12,13,Faf Du Plessis RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21
13,14,Phil Salt KKR,435,12,12,1,89,39.55,239,182.00,0,4,50,24
14,15,Yashasvi Jaiswal RR,435,16,15,1,104,31.07,279,155.91,1,1,54,16
18,19,Shivam Dube CSK,396,14,14,3,66,36.00,244,162.29,0,3,28,28
19,20,Rajat Patidar RCB,395,15,13,0,55,30.38,223,177.13,0,5,21,33
21,22,Tristan Stubbs DC,378,14,13,6,71,54.00,198,190.90,0,3,24,26
22,23,Venkatesh Iyer KKR,370,15,13,5,70,46.25,233,158.79,0,4,35,19
24,25,Shashank Singh PBKS,354,14,14,6,68,44.25,215,164.65,0,2,28,21
26,27,Suryakumar Yadav MI,345,11,11,1,102,34.50,206,167.47,1,3,36,18
27,28,Prabhsimran Singh PBKS,334,14,14,0,71,23.86,213,156.80,0,2,34,20
28,29,Jake Fraser - McGurk DC,330,9,9,0,84,36.67,141,234.04,0,4,32,28
29,30,Abishek Porel DC,327,14,12,2,65,32.70,205,159.51,0,2,36,13
30,31,Dinesh Karthik RCB,326,15,13,4,83,36.22,174,187.35,0,2,27,22
34,35,Jonny Bairstow PBKS,298,11,11,1,108,29.80,195,152.82,1,0,33,14
40,41,Tim David MI,241,13,11,3,45,30.13,152,158.55,0,0,14,15
43,44,Will Jacks RCB,230,8,8,1,100,32.86,131,175.57,1,1,16,18
44,45,Andre Russell KKR,222,15,9,2,64,31.71,120,185.00,0,1,20,16
45,46,Rachin Ravindra CSK,222,10,10,0,61,22.20,138,160.86,0,1,22,12
49,50,Rilee Rossouw PBKS,211,8,8,0,61,26.38,116,181.89,0,1,25,11
50,51,David Miller GT,210,9,9,3,55,35.00,139,151.07,0,1,20,8
51,52,Prithvi Shaw DC,198,8,8,0,66,24.75,121,163.63,0,1,30,5
53,54,Ashutosh Sharma PBKS,189,11,9,2,61,27.00,113,167.25,0,1,10,15
57,58,Abdul Samad SRH,182,16,12,2,37,18.20,108,168.51,0,0,15,11
61,62,Angkrish Raghuvanshi KKR,163,10,7,0,54,23.29,105,155.23,0,1,16,8
62,63,MS Dhoni CSK,161,14,11,8,37,53.67,73,220.54,0,0,14,13
65,66,Naman Dhir MI,140,7,7,1,62,23.33,79,177.21,0,1,12,10
70,71,Shahrukh Khan GT,127,7,7,0,58,18.14,75,169.33,0,1,9,9
71,72,Ramandeep Singh KKR,125,15,9,5,35,31.25,62,201.61,0,0,5,12
72,73,Mahipal Lomror RCB,125,10,10,2,33,15.63,68,183.82,0,0,9,9
73,74,Shimron Hetmyer RR,113,12,9,4,27,22.60,69,163.76,0,0,9,7
76,77,Rovman Powell RR,103,10,7,1,27,17.17,68,151.47,0,0,10,6
80,81,Arshad Khan LSG,83,4,4,2,58,41.50,54,153.70,0,1,6,5
86,87,Mitchell Marsh DC,61,4,4,0,23,15.25,38,160.52,0,0,9,3
87,88,Atharva Taide PBKS,61,2,2,0,46,30.50,39,156.41,0,0,7,2
88,89,Romario Shepherd MI,57,6,5,3,39,28.50,21,271.42,0,0,5,5
98,99,Swapnil Singh RCB,37,7,5,3,15,18.50,21,176.19,0,0,3,3
100,101,Shubham Dubey RR,33,4,3,1,25,16.50,19,173.68,0,0,3,2
101,102,Karn Sharma RCB,31,9,3,0,20,10.33,15,206.66,0,0,2,3
123,124,Sai Kishore GT,13,5,2,1,13,13.00,6,216.66,0,0,0,2
129,130,Avesh Khan RR,10,16,3,3,7,0.00,5,200.00,0,0,1,0
131,132,Luke Wood MI,9,2,1,1,9,0.00,3,300.00,0,0,0,1
151,152,Mohsin Khan LSG,2,9,1,0,2,2.00,1,200.00,0,0,0,0

### Q8. [Basic] Use query() to find players with Runs > 300 and SR > 140

In [85]:
# Your code here
df.query("Runs > 300 and SR > 140")

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24
5,6,Sai Sudharsan GT,527,12,12,1,103,47.91,373,141.28,1,2,48,16
7,8,Nicholas Pooran LSG,499,14,14,6,75,62.38,280,178.21,0,3,35,36
8,9,Sunil Narine KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33
9,10,Abhishek Sharma SRH,484,16,16,1,75,32.27,237,204.21,0,3,36,42
10,11,Heinrich Klaasen SRH,479,16,15,3,80,39.92,280,171.07,0,4,19,38
11,12,Rishabh Pant DC,446,13,13,2,88,40.55,287,155.40,0,3,36,25
12,13,Faf Du Plessis RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21
13,14,Phil Salt KKR,435,12,12,1,89,39.55,239,182.00,0,4,50,24
14,15,Yashasvi Jaiswal RR,435,16,15,1,104,31.07,279,155.91,1,1,54,16
15,16,Shubman Gill GT,426,12,12,1,104,38.73,289,147.40,1,2,37,15
16,17,Rohit Sharma MI,417,14,14,1,105,32.08,278,150.00,1,1,45,23
17,18,Tilak Varma MI,416,13,13,3,65,41.60,278,149.64,0,3,35,19
18,19,Shivam Dube CSK,396,14,14,3,66,36.00,244,162.29,0,3,28,28
19,20,Rajat Patidar RCB,395,15,13,0,55,30.38,223,177.13,0,5,21,33
20,21,Marcus Stoinis LSG,388,14,14,2,124,32.33,263,147.52,1,2,39,16
21,22,Tristan Stubbs DC,378,14,13,6,71,54.00,198,190.90,0,3,24,26
22,23,Venkatesh Iyer KKR,370,15,13,5,70,46.25,233,158.79,0,4,35,19
23,24,Jos Buttler RR,359,11,11,2,107,39.89,255,140.78,2,0,36,12
24,25,Shashank Singh PBKS,354,14,14,6,68,44.25,215,164.65,0,2,28,21
25,26,Shreyas Iyer KKR,351,15,14,5,58,39.00,239,146.86,0,2,34,14
26,27,Suryakumar Yadav MI,345,11,11,1,102,34.50,206,167.47,1,3,36,18
27,28,Prabhsimran Singh PBKS,334,14,14,0,71,23.86,213,156.80,0,2,34,20
28,29,Jake Fraser - McGurk DC,330,9,9,0,84,36.67,141,234.04,0,4,32,28
29,30,Abishek Porel DC,327,14,12,2,65,32.70,205,159.51,0,2,36,13
30,31,Dinesh Karthik RCB,326,15,13,4,83,36.22,174,187.35,0,2,27,22
31,32,Ishan Kishan MI,320,14,14,0,69,22.86,215,148.83,0,1,35,16
32,33,Daryl Mitchell CSK,318,13,13,2,63,28.91,223,142.60,0,2,27,10
33,34,Nitish Kumar Reddy SRH,303,13,11,2,76,33.67,212,142.92,0,2,15,21

### Q9. [Basic] Select the Runs value of the player in position 1 (POS=1) using loc

In [86]:
# Hint: df.loc[df['POS']==1, 'Runs']
df.loc[df['POS']==1,'Runs']

0    741
Name: Runs, dtype: int64

### Q10. [Basic] Get all players NOT in top 10 (POS > 10)

In [87]:
# Your code here
df[df['POS']>10]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
10,11,Heinrich Klaasen SRH,479,16,15,3,80,39.92,280,171.07,0,4,19,38
11,12,Rishabh Pant DC,446,13,13,2,88,40.55,287,155.40,0,3,36,25
12,13,Faf Du Plessis RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21
13,14,Phil Salt KKR,435,12,12,1,89,39.55,239,182.00,0,4,50,24
14,15,Yashasvi Jaiswal RR,435,16,15,1,104,31.07,279,155.91,1,1,54,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,Lizaad Williams DC,1,2,1,1,1,0.00,2,50.00,0,0,0,0
163,164,Keshav Maharaj RR,1,2,1,0,1,1.00,2,50.00,0,0,0,0
164,165,Manav Suthar GT,1,1,1,0,1,1.00,2,50.00,0,0,0,0
165,166,Vyshak Vijaykumar RCB,1,4,2,1,1,1.00,3,33.33,0,0,0,0
166,167,Ishant Sharma DC,1,9,2,2,1,0.00,7,14.28,0,0,0,0

### Q11. [Intermediate] Filter players who scored both centuries AND half-centuries (100 > 0 AND 50 > 0)

In [88]:
# Your code here
df[(df['100']>0) & (df['50']>0)]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
5,6,Sai Sudharsan GT,527,12,12,1,103,47.91,373,141.28,1,2,48,16
8,9,Sunil Narine KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33
14,15,Yashasvi Jaiswal RR,435,16,15,1,104,31.07,279,155.91,1,1,54,16
15,16,Shubman Gill GT,426,12,12,1,104,38.73,289,147.40,1,2,37,15
16,17,Rohit Sharma MI,417,14,14,1,105,32.08,278,150.00,1,1,45,23
20,21,Marcus Stoinis LSG,388,14,14,2,124,32.33,263,147.52,1,2,39,16
26,27,Suryakumar Yadav MI,345,11,11,1,102,34.50,206,167.47,1,3,36,18
43,44,Will Jacks RCB,230,8,8,1,100,32.86,131,175.57,1,1,16,18

### Q12. [Intermediate] Use isin() to filter players from RCB, CSK, or MI (teams in Player column)

In [89]:
# Extract team from Player name (last word)
df['Team'] = df['Player'].str.split().str[-1]
teams = ['RCB', 'CSK', 'MI']
# Your filter here
df[df["Player"].isin(teams)]
df[df["Team"].isin(teams)]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38,RCB
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18,CSK
12,13,Faf Du Plessis RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21,RCB
16,17,Rohit Sharma MI,417,14,14,1,105,32.08,278,150.00,1,1,45,23,MI
17,18,Tilak Varma MI,416,13,13,3,65,41.60,278,149.64,0,3,35,19,MI
18,19,Shivam Dube CSK,396,14,14,3,66,36.00,244,162.29,0,3,28,28,CSK
19,20,Rajat Patidar RCB,395,15,13,0,55,30.38,223,177.13,0,5,21,33,RCB
26,27,Suryakumar Yadav MI,345,11,11,1,102,34.50,206,167.47,1,3,36,18,MI
30,31,Dinesh Karthik RCB,326,15,13,4,83,36.22,174,187.35,0,2,27,22,RCB
31,32,Ishan Kishan MI,320,14,14,0,69,22.86,215,148.83,0,1,35,16,MI
32,33,Daryl Mitchell CSK,318,13,13,2,63,28.91,223,142.60,0,2,27,10,CSK
36,37,Ravindra Jadeja CSK,267,14,11,5,57,44.50,187,142.78,0,1,22,8,CSK
37,38,Cameron Green RCB,255,13,12,4,46,31.88,178,143.25,0,0,22,10,RCB
39,40,Ajinkya Rahane CSK,242,13,12,0,45,20.17,196,123.46,0,0,23,7,CSK
40,41,Tim David MI,241,13,11,3,45,30.13,152,158.55,0,0,14,15,MI
43,44,Will Jacks RCB,230,8,8,1,100,32.86,131,175.57,1,1,16,18,RCB
45,46,Rachin Ravindra CSK,222,10,10,0,61,22.20,138,160.86,0,1,22,12,CSK
47,48,Hardik Pandya MI,216,14,13,1,46,18.00,151,143.04,0,0,17,11,MI
62,63,MS Dhoni CSK,161,14,11,8,37,53.67,73,220.54,0,0,14,13,CSK
65,66,Naman Dhir MI,140,7,7,1,62,23.33,79,177.21,0,1,12,10,MI
69,70,Moeen Ali CSK,128,8,5,0,56,25.60,98,130.61,0,1,7,8,CSK
72,73,Mahipal Lomror RCB,125,10,10,2,33,15.63,68,183.82,0,0,9,9,RCB
75,76,Nehal Wadhera MI,109,6,6,0,49,18.17,84,129.76,0,0,9,6,MI
78,79,Anuj Rawat RCB,98,5,5,1,48,24.50,77,127.27,0,0,10,3,RCB
83,84,Dewald Brevis MI,69,3,3,0,46,23.00,59,116.94,0,0,3,5,MI
88,89,Romario Shepherd MI,57,6,5,3,39,28.50,21,271.42,0,0,5,5,MI
89,90,Glenn Maxwell RCB,52,10,9,0,28,5.78,43,120.93,0,0,6,2,RCB
90,91,Sameer Rizwi CSK,51,8,5,1,21,12.75,43,118.60,0,0,4,2,CSK
98,99,Swapnil Singh RCB,37,7,5,3,15,18.50,21,176.19,0,0,3,3,RCB
99,100,Mohammad Nabi MI,35,7,5,1,23,8.75,31,112.90,0,0,2,2,MI
101,102,Karn Sharma RCB,31,9,3,0,20,10.33,15,206.66,0,0,2,3,RCB
105,106,Suyash S Prabhudessai RCB,24,1,1,0,24,24.00,18,133.33,0,0,3,0,RCB
111,112,Shardul Thakur CSK,21,9,3,2,17,21.00,17,123.52,0,0,2,1,CSK
116,117,Saurav Chauhan RCB,18,3,3,0,9,6.00,15,120.00,0,0,1,1,RCB
118,119,Piyush Chawla MI,15,11,6,2,10,3.75,15,100.00,0,0,1,1,MI
121,122,Mitchell Santner CSK,14,3,3,0,11,4.67,17,82.35,0,0,1,0,CSK
122,123,Gerald Coetzee MI,14,10,5,1,8,3.50,22,63.63,0,0,0,1,MI
125,126,Mohammed Siraj RCB,12,14,3,1,12,6.00,8,150.00,0,0,0,2,RCB
127,128,Jasprit Bumrah MI,12,13,4,4,8,0.00,12,100.00,0,0,1,0,MI
131,132,Luke Wood MI,9,2,1,1,9,0.00,3,300.00,0,0,0,1,MI
141,142,Akash Madhwal MI,4,5,1,1,4,0.00,5,80.00,0,0,0,0,MI
147,148,Reece Topley RCB,3,4,1,1,3,0.00,6,50.00,0,0,0,0,RCB
152,153,Richard Gleeson CSK,2,2,1,1,2,0.00,2,100.00,0,0,0,0,CSK
154,155,Anshul Kamboj MI,2,3,1,1,2,0.00,2,100.00,0,0,0,0,MI
155,156,Akash Deep RCB,2,1,1,1,2,0.00,2,100.00,0,0,0,0,RCB
160,161,Shams Mulani MI,1,2,1,1,1,0.00,1,100.00,0,0,0,0,MI
161,162,Lockie Ferguson RCB,1,7,1,0,1,1.00,1,100.00,0,0,0,0,RCB
165,166,Vyshak Vijaykumar RCB,1,4,2,1,1,1.00,3,33.33,0,0,0,0,RCB

### Q13. [Intermediate] Select rows 5 to 15 and columns 'Player', 'Runs' using iloc

In [90]:
# Your code here
df.iloc[5:16,1:3]

                  Player  Runs
5       Sai Sudharsan GT   527
6          K L Rahul LSG   520
7    Nicholas Pooran LSG   499
8       Sunil Narine KKR   488
9    Abhishek Sharma SRH   484
10  Heinrich Klaasen SRH   479
11       Rishabh Pant DC   446
12    Faf Du Plessis RCB   438
13         Phil Salt KKR   435
14   Yashasvi Jaiswal RR   435
15       Shubman Gill GT   426

### Q14. [Intermediate] Filter players where Runs is between 200 and 500 using between()

In [91]:
# Hint: df['Runs'].between(200, 500)
df.loc[(df['Runs'].between(200,500))]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team
7,8,Nicholas Pooran LSG,499,14,14,6,75,62.38,280,178.21,0,3,35,36,LSG
8,9,Sunil Narine KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33,KKR
9,10,Abhishek Sharma SRH,484,16,16,1,75,32.27,237,204.21,0,3,36,42,SRH
10,11,Heinrich Klaasen SRH,479,16,15,3,80,39.92,280,171.07,0,4,19,38,SRH
11,12,Rishabh Pant DC,446,13,13,2,88,40.55,287,155.40,0,3,36,25,DC
12,13,Faf Du Plessis RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21,RCB
13,14,Phil Salt KKR,435,12,12,1,89,39.55,239,182.00,0,4,50,24,KKR
14,15,Yashasvi Jaiswal RR,435,16,15,1,104,31.07,279,155.91,1,1,54,16,RR
15,16,Shubman Gill GT,426,12,12,1,104,38.73,289,147.40,1,2,37,15,GT
16,17,Rohit Sharma MI,417,14,14,1,105,32.08,278,150.00,1,1,45,23,MI
17,18,Tilak Varma MI,416,13,13,3,65,41.60,278,149.64,0,3,35,19,MI
18,19,Shivam Dube CSK,396,14,14,3,66,36.00,244,162.29,0,3,28,28,CSK
19,20,Rajat Patidar RCB,395,15,13,0,55,30.38,223,177.13,0,5,21,33,RCB
20,21,Marcus Stoinis LSG,388,14,14,2,124,32.33,263,147.52,1,2,39,16,LSG
21,22,Tristan Stubbs DC,378,14,13,6,71,54.00,198,190.90,0,3,24,26,DC
22,23,Venkatesh Iyer KKR,370,15,13,5,70,46.25,233,158.79,0,4,35,19,KKR
23,24,Jos Buttler RR,359,11,11,2,107,39.89,255,140.78,2,0,36,12,RR
24,25,Shashank Singh PBKS,354,14,14,6,68,44.25,215,164.65,0,2,28,21,PBKS
25,26,Shreyas Iyer KKR,351,15,14,5,58,39.00,239,146.86,0,2,34,14,KKR
26,27,Suryakumar Yadav MI,345,11,11,1,102,34.50,206,167.47,1,3,36,18,MI
27,28,Prabhsimran Singh PBKS,334,14,14,0,71,23.86,213,156.80,0,2,34,20,PBKS
28,29,Jake Fraser - McGurk DC,330,9,9,0,84,36.67,141,234.04,0,4,32,28,DC
29,30,Abishek Porel DC,327,14,12,2,65,32.70,205,159.51,0,2,36,13,DC
30,31,Dinesh Karthik RCB,326,15,13,4,83,36.22,174,187.35,0,2,27,22,RCB
31,32,Ishan Kishan MI,320,14,14,0,69,22.86,215,148.83,0,1,35,16,MI
32,33,Daryl Mitchell CSK,318,13,13,2,63,28.91,223,142.60,0,2,27,10,CSK
33,34,Nitish Kumar Reddy SRH,303,13,11,2,76,33.67,212,142.92,0,2,15,21,SRH
34,35,Jonny Bairstow PBKS,298,11,11,1,108,29.80,195,152.82,1,0,33,14,PBKS
35,36,Sam Curran PBKS,270,13,12,2,63,27.00,219,123.28,0,2,24,6,PBKS
36,37,Ravindra Jadeja CSK,267,14,11,5,57,44.50,187,142.78,0,1,22,8,CSK
37,38,Cameron Green RCB,255,13,12,4,46,31.88,178,143.25,0,0,22,10,RCB
38,39,Quinton De Kock LSG,250,11,11,0,81,22.73,186,134.40,0,3,29,9,LSG
39,40,Ajinkya Rahane CSK,242,13,12,0,45,20.17,196,123.46,0,0,23,7,CSK
40,41,Tim David MI,241,13,11,3,45,30.13,152,158.55,0,0,14,15,MI
41,42,Ayush Badoni LSG,235,14,12,4,55,29.38,171,137.42,0,2,22,5,LSG
42,43,Axar Patel DC,235,14,12,4,66,29.38,179,131.28,0,2,19,10,DC
43,44,Will Jacks RCB,230,8,8,1,100,32.86,131,175.57,1,1,16,18,RCB
44,45,Andre Russell KKR,222,15,9,2,64,31.71,120,185.00,0,1,20,16,KKR
45,46,Rachin Ravindra CSK,222,10,10,0,61,22.20,138,160.86,0,1,22,12,CSK
46,47,Aiden Markram SRH,220,11,11,2,50,24.44,177,124.29,0,1,18,4,SRH
47,48,Hardik Pandya MI,216,14,13,1,46,18.00,151,143.04,0,0,17,11,MI
48,49,Shahbaz Ahmed SRH,215,16,12,3,59,23.89,166,129.51,0,1,7,13,SRH
49,50,Rilee Rossouw PBKS,211,8,8,0,61,26.38,116,181.89,0,1,25,11,PBKS
50,51,David Miller GT,210,9,9,3,55,35.00,139,151.07,0,1,20,8,GT

### Q15. [Intermediate] Find players whose name contains 'Sharma' (use str.contains)

In [92]:
# Your code here
df.loc[df['Player'].str.contains('Sharma')]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team
9,10,Abhishek Sharma SRH,484,16,16,1,75,32.27,237,204.21,0,3,36,42,SRH
16,17,Rohit Sharma MI,417,14,14,1,105,32.08,278,150.00,1,1,45,23,MI
53,54,Ashutosh Sharma PBKS,189,11,9,2,61,27.00,113,167.25,0,1,10,15,PBKS
55,56,Jitesh Sharma PBKS,187,14,12,1,32,17.00,142,131.69,0,0,9,12,PBKS
101,102,Karn Sharma RCB,31,9,3,0,20,10.33,15,206.66,0,0,2,3,RCB
145,146,Mohit Sharma GT,4,12,3,1,4,2.00,15,26.66,0,0,0,0,GT
166,167,Ishant Sharma DC,1,9,2,2,1,0.00,7,14.28,0,0,0,0,DC

### Q16. [Intermediate] Filter using query(): players with Avg > 30 and Mat >= 10 and SR > 130

In [93]:
# Your code here
df.query("Avg>30 & Mat>=10 & SR>130").reset_index()

,index,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team
0,0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38,RCB
1,1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18,CSK
2,2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33,RR
3,3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32,SRH
4,4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24,RR
5,5,6,Sai Sudharsan GT,527,12,12,1,103,47.91,373,141.28,1,2,48,16,GT
6,6,7,K L Rahul LSG,520,14,14,0,82,37.14,382,136.12,0,4,45,19,LSG
7,7,8,Nicholas Pooran LSG,499,14,14,6,75,62.38,280,178.21,0,3,35,36,LSG
8,8,9,Sunil Narine KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33,KKR
9,9,10,Abhishek Sharma SRH,484,16,16,1,75,32.27,237,204.21,0,3,36,42,SRH
10,10,11,Heinrich Klaasen SRH,479,16,15,3,80,39.92,280,171.07,0,4,19,38,SRH
11,11,12,Rishabh Pant DC,446,13,13,2,88,40.55,287,155.40,0,3,36,25,DC
12,13,14,Phil Salt KKR,435,12,12,1,89,39.55,239,182.00,0,4,50,24,KKR
13,14,15,Yashasvi Jaiswal RR,435,16,15,1,104,31.07,279,155.91,1,1,54,16,RR
14,15,16,Shubman Gill GT,426,12,12,1,104,38.73,289,147.40,1,2,37,15,GT
15,16,17,Rohit Sharma MI,417,14,14,1,105,32.08,278,150.00,1,1,45,23,MI
16,17,18,Tilak Varma MI,416,13,13,3,65,41.60,278,149.64,0,3,35,19,MI
17,18,19,Shivam Dube CSK,396,14,14,3,66,36.00,244,162.29,0,3,28,28,CSK
18,19,20,Rajat Patidar RCB,395,15,13,0,55,30.38,223,177.13,0,5,21,33,RCB
19,20,21,Marcus Stoinis LSG,388,14,14,2,124,32.33,263,147.52,1,2,39,16,LSG
20,21,22,Tristan Stubbs DC,378,14,13,6,71,54.00,198,190.90,0,3,24,26,DC
21,22,23,Venkatesh Iyer KKR,370,15,13,5,70,46.25,233,158.79,0,4,35,19,KKR
22,23,24,Jos Buttler RR,359,11,11,2,107,39.89,255,140.78,2,0,36,12,RR
23,24,25,Shashank Singh PBKS,354,14,14,6,68,44.25,215,164.65,0,2,28,21,PBKS
24,25,26,Shreyas Iyer KKR,351,15,14,5,58,39.00,239,146.86,0,2,34,14,KKR
25,26,27,Suryakumar Yadav MI,345,11,11,1,102,34.50,206,167.47,1,3,36,18,MI
26,29,30,Abishek Porel DC,327,14,12,2,65,32.70,205,159.51,0,2,36,13,DC
27,30,31,Dinesh Karthik RCB,326,15,13,4,83,36.22,174,187.35,0,2,27,22,RCB
28,33,34,Nitish Kumar Reddy SRH,303,13,11,2,76,33.67,212,142.92,0,2,15,21,SRH
29,36,37,Ravindra Jadeja CSK,267,14,11,5,57,44.50,187,142.78,0,1,22,8,CSK
30,37,38,Cameron Green RCB,255,13,12,4,46,31.88,178,143.25,0,0,22,10,RCB
31,40,41,Tim David MI,241,13,11,3,45,30.13,152,158.55,0,0,14,15,MI
32,44,45,Andre Russell KKR,222,15,9,2,64,31.71,120,185.00,0,1,20,16,KKR
33,62,63,MS Dhoni CSK,161,14,11,8,37,53.67,73,220.54,0,0,14,13,CSK
34,71,72,Ramandeep Singh KKR,125,15,9,5,35,31.25,62,201.61,0,0,5,12,KKR
35,82,83,Harpreet Brar PBKS,75,13,7,5,29,37.50,54,138.88,0,0,8,2,PBKS

### Q17. [Intermediate] Select every alternate row (even-indexed) using iloc

In [94]:
# Hint: df.iloc[::2]
df.iloc[::2]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38,RCB
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33,RR
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24,RR
6,7,K L Rahul LSG,520,14,14,0,82,37.14,382,136.12,0,4,45,19,LSG
8,9,Sunil Narine KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33,KKR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,159,B R Sharath GT,2,1,1,0,2,2.00,5,40.00,0,0,0,0,GT
160,161,Shams Mulani MI,1,2,1,1,1,0.00,1,100.00,0,0,0,0,MI
162,163,Lizaad Williams DC,1,2,1,1,1,0.00,2,50.00,0,0,0,0,DC
164,165,Manav Suthar GT,1,1,1,0,1,1.00,2,50.00,0,0,0,0,GT
166,167,Ishant Sharma DC,1,9,2,2,1,0.00,7,14.28,0,0,0,0,DC

### Q18. [Intermediate] Filter players ranked in top 20 OR with more than 2 centuries

In [95]:
# Your code here
df.loc[(df['POS']>=20) | (df['100']>2)]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team
19,20,Rajat Patidar RCB,395,15,13,0,55,30.38,223,177.13,0,5,21,33,RCB
20,21,Marcus Stoinis LSG,388,14,14,2,124,32.33,263,147.52,1,2,39,16,LSG
21,22,Tristan Stubbs DC,378,14,13,6,71,54.00,198,190.90,0,3,24,26,DC
22,23,Venkatesh Iyer KKR,370,15,13,5,70,46.25,233,158.79,0,4,35,19,KKR
23,24,Jos Buttler RR,359,11,11,2,107,39.89,255,140.78,2,0,36,12,RR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,Lizaad Williams DC,1,2,1,1,1,0.00,2,50.00,0,0,0,0,DC
163,164,Keshav Maharaj RR,1,2,1,0,1,1.00,2,50.00,0,0,0,0,RR
164,165,Manav Suthar GT,1,1,1,0,1,1.00,2,50.00,0,0,0,0,GT
165,166,Vyshak Vijaykumar RCB,1,4,2,1,1,1.00,3,33.33,0,0,0,0,RCB
166,167,Ishant Sharma DC,1,9,2,2,1,0.00,7,14.28,0,0,0,0,DC

### Q19. [Advanced] Use np.where to create a 'Category' column: 'Elite' if Runs>400, 'Good' if >200, else 'Average'

In [96]:
# Hint: use nested np.where
df['Category'] = np.where(
    df['Runs'] > 400,
    'Elite',
    np.where(df['Runs'] > 200, 'Good', 'Average')
)

### Q20. [Advanced] Filter players in bottom 10% of Runs using quantile

In [97]:
# Hint: df['Runs'].quantile(0.10)
df['Runs'].quantile(0.10)

np.float64(3.0)

### Q21. [Advanced] Use .loc with a boolean Series to find players whose 4s > 2 * 6s (more boundaries than sixes doubled)

In [98]:
df.loc[df['4s'] > 2 * df['6s']]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team,Category
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18,CSK,Elite
5,6,Sai Sudharsan GT,527,12,12,1,103,47.91,373,141.28,1,2,48,16,GT,Elite
6,7,K L Rahul LSG,520,14,14,0,82,37.14,382,136.12,0,4,45,19,LSG,Elite
12,13,Faf Du Plessis RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21,RCB,Elite
13,14,Phil Salt KKR,435,12,12,1,89,39.55,239,182.00,0,4,50,24,KKR,Elite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,135,Abhinav Manohar GT,9,2,2,0,8,4.50,16,56.25,0,0,1,0,GT,Average
137,138,Spencer Johnson GT,6,5,3,3,5,0.00,7,85.71,0,0,1,0,GT,Average
138,139,Anmolpreet Singh SRH,5,2,2,0,5,2.50,6,83.33,0,0,1,0,SRH,Average
139,140,Noor Ahmad GT,5,10,4,2,4,2.50,9,55.55,0,0,1,0,GT,Average
140,141,Arshdeep Singh PBKS,4,14,1,0,4,4.00,3,133.33,0,0,1,0,PBKS,Average

### Q22. [Advanced] Select the last column and last 5 rows using negative iloc indexing

In [99]:
# Your code here
df.iloc[-5:,-1]

162    Average
163    Average
164    Average
165    Average
166    Average
Name: Category, dtype: str

### Q23. [Advanced] Filter players who are in top 25% for both Runs AND SR simultaneously

In [100]:
# Your code here
df[
    (df['Runs'] >= df['Runs'].quantile(0.75)) &
    (df['SR'] >= df['SR'].quantile(0.75))
]

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team,Category
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32,SRH,Elite
7,8,Nicholas Pooran LSG,499,14,14,6,75,62.38,280,178.21,0,3,35,36,LSG,Elite
8,9,Sunil Narine KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33,KKR,Elite
9,10,Abhishek Sharma SRH,484,16,16,1,75,32.27,237,204.21,0,3,36,42,SRH,Elite
10,11,Heinrich Klaasen SRH,479,16,15,3,80,39.92,280,171.07,0,4,19,38,SRH,Elite
12,13,Faf Du Plessis RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21,RCB,Elite
13,14,Phil Salt KKR,435,12,12,1,89,39.55,239,182.00,0,4,50,24,KKR,Elite
14,15,Yashasvi Jaiswal RR,435,16,15,1,104,31.07,279,155.91,1,1,54,16,RR,Elite
18,19,Shivam Dube CSK,396,14,14,3,66,36.00,244,162.29,0,3,28,28,CSK,Good
19,20,Rajat Patidar RCB,395,15,13,0,55,30.38,223,177.13,0,5,21,33,RCB,Good
21,22,Tristan Stubbs DC,378,14,13,6,71,54.00,198,190.90,0,3,24,26,DC,Good
22,23,Venkatesh Iyer KKR,370,15,13,5,70,46.25,233,158.79,0,4,35,19,KKR,Good
24,25,Shashank Singh PBKS,354,14,14,6,68,44.25,215,164.65,0,2,28,21,PBKS,Good
26,27,Suryakumar Yadav MI,345,11,11,1,102,34.50,206,167.47,1,3,36,18,MI,Good
27,28,Prabhsimran Singh PBKS,334,14,14,0,71,23.86,213,156.80,0,2,34,20,PBKS,Good
28,29,Jake Fraser - McGurk DC,330,9,9,0,84,36.67,141,234.04,0,4,32,28,DC,Good
29,30,Abishek Porel DC,327,14,12,2,65,32.70,205,159.51,0,2,36,13,DC,Good
30,31,Dinesh Karthik RCB,326,15,13,4,83,36.22,174,187.35,0,2,27,22,RCB,Good
40,41,Tim David MI,241,13,11,3,45,30.13,152,158.55,0,0,14,15,MI,Good

### Q24. [Advanced] Use .pipe() to apply a filtering function to the DataFrame

In [101]:
def filter_elite(df, min_runs=400, min_sr=140):
    return df[(df['Runs'] >= min_runs) & (df['SR'] >= min_sr)]

# Use pipe here
df.pipe(filter_elite)

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team,Category
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38,RCB,Elite
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18,CSK,Elite
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33,RR,Elite
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32,SRH,Elite
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24,RR,Elite
5,6,Sai Sudharsan GT,527,12,12,1,103,47.91,373,141.28,1,2,48,16,GT,Elite
7,8,Nicholas Pooran LSG,499,14,14,6,75,62.38,280,178.21,0,3,35,36,LSG,Elite
8,9,Sunil Narine KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33,KKR,Elite
9,10,Abhishek Sharma SRH,484,16,16,1,75,32.27,237,204.21,0,3,36,42,SRH,Elite
10,11,Heinrich Klaasen SRH,479,16,15,3,80,39.92,280,171.07,0,4,19,38,SRH,Elite
11,12,Rishabh Pant DC,446,13,13,2,88,40.55,287,155.40,0,3,36,25,DC,Elite
12,13,Faf Du Plessis RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21,RCB,Elite
13,14,Phil Salt KKR,435,12,12,1,89,39.55,239,182.00,0,4,50,24,KKR,Elite
14,15,Yashasvi Jaiswal RR,435,16,15,1,104,31.07,279,155.91,1,1,54,16,RR,Elite
15,16,Shubman Gill GT,426,12,12,1,104,38.73,289,147.40,1,2,37,15,GT,Elite
16,17,Rohit Sharma MI,417,14,14,1,105,32.08,278,150.00,1,1,45,23,MI,Elite
17,18,Tilak Varma MI,416,13,13,3,65,41.60,278,149.64,0,3,35,19,MI,Elite

### Q25. [Advanced] Chain multiple filters: top 50 players, SR > 130, Avg > 25, sorted by 6s descending

In [102]:
# Your code here
(
    df.head(50)
      .loc[(df.head(50)['SR'] > 130) & (df.head(50)['Avg'] > 25)]
      .sort_values(by='6s', ascending=False)
)

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team,Category
9,10,Abhishek Sharma SRH,484,16,16,1,75,32.27,237,204.21,0,3,36,42,SRH,Elite
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38,RCB,Elite
10,11,Heinrich Klaasen SRH,479,16,15,3,80,39.92,280,171.07,0,4,19,38,SRH,Elite
7,8,Nicholas Pooran LSG,499,14,14,6,75,62.38,280,178.21,0,3,35,36,LSG,Elite
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33,RR,Elite
19,20,Rajat Patidar RCB,395,15,13,0,55,30.38,223,177.13,0,5,21,33,RCB,Good
8,9,Sunil Narine KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33,KKR,Elite
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32,SRH,Elite
18,19,Shivam Dube CSK,396,14,14,3,66,36.00,244,162.29,0,3,28,28,CSK,Good
28,29,Jake Fraser - McGurk DC,330,9,9,0,84,36.67,141,234.04,0,4,32,28,DC,Good
21,22,Tristan Stubbs DC,378,14,13,6,71,54.00,198,190.90,0,3,24,26,DC,Good
11,12,Rishabh Pant DC,446,13,13,2,88,40.55,287,155.40,0,3,36,25,DC,Elite
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24,RR,Elite
13,14,Phil Salt KKR,435,12,12,1,89,39.55,239,182.00,0,4,50,24,KKR,Elite
16,17,Rohit Sharma MI,417,14,14,1,105,32.08,278,150.00,1,1,45,23,MI,Elite
30,31,Dinesh Karthik RCB,326,15,13,4,83,36.22,174,187.35,0,2,27,22,RCB,Good
12,13,Faf Du Plessis RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21,RCB,Elite
33,34,Nitish Kumar Reddy SRH,303,13,11,2,76,33.67,212,142.92,0,2,15,21,SRH,Good
24,25,Shashank Singh PBKS,354,14,14,6,68,44.25,215,164.65,0,2,28,21,PBKS,Good
6,7,K L Rahul LSG,520,14,14,0,82,37.14,382,136.12,0,4,45,19,LSG,Elite
17,18,Tilak Varma MI,416,13,13,3,65,41.60,278,149.64,0,3,35,19,MI,Elite
22,23,Venkatesh Iyer KKR,370,15,13,5,70,46.25,233,158.79,0,4,35,19,KKR,Good
26,27,Suryakumar Yadav MI,345,11,11,1,102,34.50,206,167.47,1,3,36,18,MI,Good
43,44,Will Jacks RCB,230,8,8,1,100,32.86,131,175.57,1,1,16,18,RCB,Good
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18,CSK,Elite
44,45,Andre Russell KKR,222,15,9,2,64,31.71,120,185.00,0,1,20,16,KKR,Good
20,21,Marcus Stoinis LSG,388,14,14,2,124,32.33,263,147.52,1,2,39,16,LSG,Good
14,15,Yashasvi Jaiswal RR,435,16,15,1,104,31.07,279,155.91,1,1,54,16,RR,Elite
5,6,Sai Sudharsan GT,527,12,12,1,103,47.91,373,141.28,1,2,48,16,GT,Elite
15,16,Shubman Gill GT,426,12,12,1,104,38.73,289,147.40,1,2,37,15,GT,Elite
40,41,Tim David MI,241,13,11,3,45,30.13,152,158.55,0,0,14,15,MI,Good
25,26,Shreyas Iyer KKR,351,15,14,5,58,39.00,239,146.86,0,2,34,14,KKR,Good
34,35,Jonny Bairstow PBKS,298,11,11,1,108,29.80,195,152.82,1,0,33,14,PBKS,Good
29,30,Abishek Porel DC,327,14,12,2,65,32.70,205,159.51,0,2,36,13,DC,Good
23,24,Jos Buttler RR,359,11,11,2,107,39.89,255,140.78,2,0,36,12,RR,Good
49,50,Rilee Rossouw PBKS,211,8,8,0,61,26.38,116,181.89,0,1,25,11,PBKS,Good
32,33,Daryl Mitchell CSK,318,13,13,2,63,28.91,223,142.60,0,2,27,10,CSK,Good
37,38,Cameron Green RCB,255,13,12,4,46,31.88,178,143.25,0,0,22,10,RCB,Good
42,43,Axar Patel DC,235,14,12,4,66,29.38,179,131.28,0,2,19,10,DC,Good
36,37,Ravindra Jadeja CSK,267,14,11,5,57,44.50,187,142.78,0,1,22,8,CSK,Good
41,42,Ayush Badoni LSG,235,14,12,4,55,29.38,171,137.42,0,2,22,5,LSG,Good

---
# 🔧 Section 5: Feature Engineering (25 Questions)
---

### Q1. [Basic] Extract the Team name from the 'Player' column into a new column 'Team'

In [103]:
# Note: Player format is 'Name TEAM' e.g. 'Virat Kohli RCB'
df['Team'] = df['Player'].str.split().str[-1]
df[['Player','Team']].head()

                Player Team
0      Virat Kohli RCB  RCB
1  Ruturaj Gaikwad CSK  CSK
2       Riyan Parag RR   RR
3      Travis Head SRH  SRH
4      Sanju Samson RR   RR

### Q2. [Basic] Create a 'Boundary_Runs' column = (4s * 4) + (6s * 6)

In [104]:
# Your code here
df_copy = df.copy()
df_copy['Boundary_Runs']=df['4s']*4+df['6s']*6
df_copy

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team,Category,Boundary_Runs
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38,RCB,Elite,476
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18,CSK,Elite,340
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33,RR,Elite,358
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32,SRH,Elite,448
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24,RR,Elite,336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,Lizaad Williams DC,1,2,1,1,1,0.00,2,50.00,0,0,0,0,DC,Average,0
163,164,Keshav Maharaj RR,1,2,1,0,1,1.00,2,50.00,0,0,0,0,RR,Average,0
164,165,Manav Suthar GT,1,1,1,0,1,1.00,2,50.00,0,0,0,0,GT,Average,0
165,166,Vyshak Vijaykumar RCB,1,4,2,1,1,1.00,3,33.33,0,0,0,0,RCB,Average,0
166,167,Ishant Sharma DC,1,9,2,2,1,0.00,7,14.28,0,0,0,0,DC,Average,0

### Q3. [Basic] Create a 'Non_Boundary_Runs' column = Runs - Boundary_Runs

In [105]:
# Your code here
df_copy['Non-Boundary'] = df_copy['Runs']-df_copy['Boundary_Runs']

### Q4. [Basic] Create a 'Boundary_Pct' = (Boundary_Runs / Runs) * 100

In [106]:
# Your code here
df_copy['Boundary_Pct'] = (df_copy['Boundary_Runs']/df_copy['Runs'])*100
df_copy

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team,Category,Boundary_Runs,Non-Boundary,Boundary_Pct
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38,RCB,Elite,476,265,64.237517
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18,CSK,Elite,340,243,58.319039
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33,RR,Elite,358,215,62.478185
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32,SRH,Elite,448,119,79.012346
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24,RR,Elite,336,195,63.276836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,Lizaad Williams DC,1,2,1,1,1,0.00,2,50.00,0,0,0,0,DC,Average,0,1,0.000000
163,164,Keshav Maharaj RR,1,2,1,0,1,1.00,2,50.00,0,0,0,0,RR,Average,0,1,0.000000
164,165,Manav Suthar GT,1,1,1,0,1,1.00,2,50.00,0,0,0,0,GT,Average,0,1,0.000000
165,166,Vyshak Vijaykumar RCB,1,4,2,1,1,1.00,3,33.33,0,0,0,0,RCB,Average,0,1,0.000000
166,167,Ishant Sharma DC,1,9,2,2,1,0.00,7,14.28,0,0,0,0,DC,Average,0,1,0.000000

### Q5. [Basic] Rename the columns: '4s' → 'Fours', '6s' → 'Sixes'

In [107]:
# Your code here
df_copy.rename(columns={'4s':'Fours','6s':'Sixs'})

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,Fours,Sixs,Team,Category,Boundary_Runs,Non-Boundary,Boundary_Pct
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38,RCB,Elite,476,265,64.237517
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18,CSK,Elite,340,243,58.319039
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33,RR,Elite,358,215,62.478185
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32,SRH,Elite,448,119,79.012346
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24,RR,Elite,336,195,63.276836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,Lizaad Williams DC,1,2,1,1,1,0.00,2,50.00,0,0,0,0,DC,Average,0,1,0.000000
163,164,Keshav Maharaj RR,1,2,1,0,1,1.00,2,50.00,0,0,0,0,RR,Average,0,1,0.000000
164,165,Manav Suthar GT,1,1,1,0,1,1.00,2,50.00,0,0,0,0,GT,Average,0,1,0.000000
165,166,Vyshak Vijaykumar RCB,1,4,2,1,1,1.00,3,33.33,0,0,0,0,RCB,Average,0,1,0.000000
166,167,Ishant Sharma DC,1,9,2,2,1,0.00,7,14.28,0,0,0,0,DC,Average,0,1,0.000000

### Q6. [Basic] Convert the SR column from float to int using astype()

In [108]:
# Your code here
df['SR'].astype(int)

0      154
1      141
2      149
3      191
4      153
      ...
162     50
163     50
164     50
165     33
166     14
Name: SR, Length: 167, dtype: int64

### Q7. [Basic] Clean the HS column by removing the '*' character

In [109]:
# Your code here
df['HS'].replace('*',' ')

0      113
1      108
2       84
3      102
4       86
      ...
162      1
163      1
164      1
165      1
166      1
Name: HS, Length: 167, dtype: str

### Q8. [Basic] Create a 'Runs_Per_Match' column = Runs / Mat

In [110]:
# Your code here
df['Run_per_Match']= df['Runs']/df['Mat']

### Q9. [Basic] Create a binary column 'Has_Century' = 1 if 100 > 0, else 0

In [111]:
# Your code here
df['Has_century'] = np.where(df['Runs']>100,1,0)

### Q10. [Basic] Map teams to their city: {'RCB': 'Bangalore', 'CSK': 'Chennai', 'MI': 'Mumbai'} — create 'City' column

In [112]:
team_city = {'RCB': 'Bangalore', 'CSK': 'Chennai', 'MI': 'Mumbai',
             'KKR': 'Kolkata', 'DC': 'Delhi', 'SRH': 'Hyderabad',
             'RR': 'Jaipur', 'PBKS': 'Mohali', 'GT': 'Ahmedabad', 'LSG': 'Lucknow'}
# Your code here
df['City'] = df['Team'].map(team_city)
df

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team,Category,Run_per_Match,Has_century,City
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38,RCB,Elite,49.400000,1,Bangalore
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18,CSK,Elite,41.642857,1,Chennai
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33,RR,Elite,35.812500,1,Jaipur
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32,SRH,Elite,37.800000,1,Hyderabad
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24,RR,Elite,33.187500,1,Jaipur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,Lizaad Williams DC,1,2,1,1,1,0.00,2,50.00,0,0,0,0,DC,Average,0.500000,0,Delhi
163,164,Keshav Maharaj RR,1,2,1,0,1,1.00,2,50.00,0,0,0,0,RR,Average,0.500000,0,Jaipur
164,165,Manav Suthar GT,1,1,1,0,1,1.00,2,50.00,0,0,0,0,GT,Average,1.000000,0,Ahmedabad
165,166,Vyshak Vijaykumar RCB,1,4,2,1,1,1.00,3,33.33,0,0,0,0,RCB,Average,0.250000,0,Bangalore
166,167,Ishant Sharma DC,1,9,2,2,1,0.00,7,14.28,0,0,0,0,DC,Average,0.111111,0,Delhi

### Q11. [Intermediate] One-hot encode the 'Team' column using pd.get_dummies()

In [113]:
# Make sure you have the Team column first
pd.get_dummies('Team')

   Team
0  True

### Q12. [Intermediate] Bin players into 3 Runs categories using pd.cut(): 'Low' (0-100), 'Medium' (101-300), 'High' (301+)

In [114]:
# Your code here
# df['Bin'] = np.where(df['Runs']>301,'High',np.where(df['Runs']>100,'Medium','Low'))
bins = [0, 100, 300, float('inf')]
labels = ['Low', 'Medium', 'High']

df['Runs_Category'] = pd.cut(
    df['Runs'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

### Q13. [Intermediate] Use pd.qcut() to bin Runs into 4 equal-frequency quantiles

In [115]:
# Your code here
df["Runs_Category"] = pd.qcut(

    df["Runs"],

    q=4,

    labels=["Q1", "Q2", "Q3", "Q4"]

)

df.head()

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s,Team,Category,Run_per_Match,Has_century,City,Runs_Category
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,1,5,62,38,RCB,Elite,49.400000,1,Bangalore,Q4
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,1,4,58,18,CSK,Elite,41.642857,1,Chennai,Q4
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,0,4,40,33,RR,Elite,35.812500,1,Jaipur,Q4
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32,SRH,Elite,37.800000,1,Hyderabad,Q4
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24,RR,Elite,33.187500,1,Jaipur,Q4

### Q14. [Intermediate] Create 'Dismissal_Rate' = (Inns - NO) / Inns (how often they got out)

In [116]:
# Your code here
df["Dismissal_Rate"] = (df["Inns"] - df["NO"]) / df["Inns"]

### Q15. [Intermediate] Use apply() to create a 'Performance_Label' column based on Runs: >=400 → 'Excellent', >=200 → 'Good', else → 'Average'

In [117]:
def label_performance(runs):
    pass  # Fill this

df['Performance_Label'] = df['Runs'].apply(label_performance)

### Q16. [Intermediate] Clip the SR column so values below 100 become 100 and above 200 become 200

In [118]:
# Your code here

### Q17. [Intermediate] Create 'HS_numeric' by converting HS column to int after removing '*'

In [119]:
# Your code here

### Q18. [Intermediate] Label-encode the Team column (RCB→0, CSK→1, etc.) using map()

In [120]:
teams = df['Player'].str.split().str[-1].unique()
team_map = {team: i for i, team in enumerate(sorted(teams))}
# Your code here

### Q19. [Advanced] Create interaction feature: 'SR_x_Avg' = SR * Avg (for ML models)

In [121]:
# Your code here

### Q20. [Advanced] Normalize the Runs column to 0-1 range using Min-Max scaling manually

In [122]:
# Formula: (x - min) / (max - min)

### Q21. [Advanced] Standardize the SR column using Z-score normalization (subtract mean, divide by std)

In [123]:
# Your code here

### Q22. [Advanced] Create polynomial features: Runs^2, SR^2, and Runs*SR

In [124]:
# Your code here

### Q23. [Advanced] Use pd.get_dummies with drop_first=True to avoid multicollinearity in Team encoding

In [125]:
# Your code here

### Q24. [Advanced] Create log-transformed Runs feature (useful for skewed data)

In [126]:
# Hint: np.log1p(df['Runs'])

### Q25. [Advanced] Build a complete feature pipeline: extract Team, create Boundary_Runs, normalize Runs, encode Team, drop Player

In [127]:
df_ml = df.copy()
# Step 1: Extract Team
# Step 2: Create Boundary_Runs
# Step 3: Normalize Runs
# Step 4: Encode Team
# Step 5: Drop Player
# Your code here

---
# 📊 Section 6: Aggregation & GroupBy (25 Questions)
---

### Q1. [Basic] First, create a 'Team' column by extracting last word from Player

In [128]:
df['Team'] = df['Player'].str.split().str[-1]
df[['Player', 'Team']].head()

                Player Team
0      Virat Kohli RCB  RCB
1  Ruturaj Gaikwad CSK  CSK
2       Riyan Parag RR   RR
3      Travis Head SRH  SRH
4      Sanju Samson RR   RR

### Q2. [Basic] Find the total runs scored by each team using groupby

In [129]:
# Your code here

### Q3. [Basic] Find the average batting average (Avg) per team

In [130]:
# Your code here

### Q4. [Basic] Count number of players per team

In [131]:
# Your code here

### Q5. [Basic] Find the team with the highest total 6s

In [132]:
# Your code here

### Q6. [Basic] Find max Runs per team

In [133]:
# Your code here

### Q7. [Basic] Find mean SR per team, sorted descending

In [134]:
# Your code here

### Q8. [Basic] Use size() to count entries per team (different from count())

In [135]:
# Your code here

### Q9. [Basic] Find the minimum Avg per team

In [136]:
# Your code here

### Q10. [Basic] Get the sum of 4s and 6s per team

In [137]:
# Your code here

### Q11. [Intermediate] Use agg() to get mean Runs, max SR, and total 6s per team in one call

In [138]:
# Your code here

### Q12. [Intermediate] Group by Team and get the player with max Runs in each team

In [139]:
# Hint: use idxmax() after groupby

### Q13. [Intermediate] Use filter() to keep only teams that have average Runs > 150

In [140]:
# Hint: df.groupby('Team').filter(lambda x: ...)

### Q14. [Intermediate] Use transform() to add a column 'Team_Avg_Runs' = mean runs of each player's team

In [141]:
# Hint: df.groupby('Team')['Runs'].transform('mean')

### Q15. [Intermediate] Use apply() with a custom function to get the range (max-min) of Runs per team

In [142]:
# Your code here

### Q16. [Intermediate] Group by number of centuries scored and find average runs in each group

In [143]:
# Your code here

### Q17. [Intermediate] Iterate over groups and print team name and top scorer for each team

In [144]:
for team, group in df.groupby('Team'):
    # print team name and player with max runs
    pass

### Q18. [Intermediate] Use rolling(3).mean() on the Runs column (sorted by POS) to get 3-player moving average

In [145]:
# Your code here

### Q19. [Intermediate] Create a pivot table: rows=Team, columns='Has_Century' (0/1), values=mean Runs

In [146]:
df['Has_Century'] = (df['100'] > 0).astype(int)
# Your pivot table here

### Q20. [Intermediate] Use cumsum() to create cumulative runs column sorted by POS

In [147]:
# Your code here

### Q21. [Advanced] For each team, calculate what percentage of total IPL runs each team contributed

In [148]:
# Your code here

### Q22. [Advanced] Use groupby + transform to create 'Runs_vs_Team_Avg' = player runs minus their team's mean runs

In [149]:
# Your code here

### Q23. [Advanced] Use agg() with named aggregations (pandas >= 0.25) to get per-team stats

In [150]:
result = df.groupby('Team').agg(
    Total_Runs=('Runs', 'sum'),
    Best_SR=('SR', 'max'),
    Num_Players=('Player', 'count')
)
result

      Total_Runs  Best_SR  Num_Players
Team
CSK         2405   220.54           12
DC          2465   234.04           21
GT          1936   216.66           20
KKR         2481   201.61           14
LSG         2350   200.00           15
MI          2422   300.00           18
PBKS        2372   181.89           18
RCB         2789   206.66           18
RR          2533   200.00           15
SRH         2906   204.21           16

### Q24. [Advanced] Find for each team: the player with max runs AND the player with max SR (two separate things)

In [151]:
# Your code here

### Q25. [Advanced] Create a team scorecard: total runs, avg SR, most 6s, number of century-scorers, sorted by total runs

In [152]:
# Your code here

---
# 🔗 Section 7: Merging & Joining (25 Questions)
---

### Setup - Create helper DataFrames

In [153]:
# Team info DataFrame
team_info = pd.DataFrame({
    'Team': ['RCB', 'CSK', 'MI', 'KKR', 'DC', 'SRH', 'RR', 'PBKS', 'GT', 'LSG'],
    'City': ['Bangalore', 'Chennai', 'Mumbai', 'Kolkata', 'Delhi', 'Hyderabad', 'Jaipur', 'Mohali', 'Ahmedabad', 'Lucknow'],
    'Titles': [0, 5, 5, 3, 0, 1, 1, 0, 1, 0],
    'Home_Ground': ['Chinnaswamy', 'Chepauk', 'Wankhede', 'Eden Gardens', 'Kotla', 'Uppal', 'SMS', 'IS Bindra', 'Narendra Modi', 'Ekana']
})

# Top batters bowling stats (fictional)
bowling_df = pd.DataFrame({
    'Player': df['Player'].head(20).values,
    'Wickets': np.random.randint(0, 3, 20),
    'Economy': np.random.uniform(7, 12, 20).round(2)
})

df['Team'] = df['Player'].str.split().str[-1]
print('Helper DataFrames created!')

Helper DataFrames created!

### Q1. [Basic] Merge df with team_info on 'Team' column (inner join)

In [154]:
# Your code here

### Q2. [Basic] Left join df with team_info (keep all players even if team not in team_info)

In [155]:
# Your code here

### Q3. [Basic] Concatenate the top 10 and bottom 10 players into one DataFrame vertically

In [156]:
top10 = df.head(10)
bottom10 = df.tail(10)
# Your code here

### Q4. [Basic] Merge df with bowling_df on 'Player' to add bowling stats to batting stats

In [157]:
# Your code here

### Q5. [Basic] Use pd.concat to combine top 5, middle 5, and bottom 5 players

In [158]:
# Your code here

### Q6. [Basic] Right join: keep all teams in team_info even if no player data exists

In [159]:
# Your code here

### Q7. [Basic] Full outer join between a subset of df and team_info

In [160]:
# Your code here

### Q8. [Basic] Concatenate df with itself and reset the index

In [161]:
# Your code here

### Q9. [Basic] After merging with team_info, select only: Player, Runs, Team, City, Titles

In [162]:
# Your code here

### Q10. [Basic] Merge and check which players have NaN in 'City' after join

In [163]:
# Your code here

### Q11. [Intermediate] Use suffixes parameter when merging two versions of df on Player (to avoid column name collision)

In [164]:
df_v1 = df[['Player', 'Runs']].copy()
df_v2 = df[['Player', 'Runs']].copy()
df_v2['Runs'] = df_v2['Runs'] * 0.9  # simulated updated runs
# Merge with suffixes

### Q12. [Intermediate] Merge df with team_info and find teams with most players AND most titles

In [165]:
# Your code here

### Q13. [Intermediate] Use concat with axis=1 to add the 'Titles' column from team_info to df

In [166]:
# Hint: merge, then use concat along axis=1

### Q14. [Intermediate] After merging, find the correlation between player Runs and their team's Titles

In [167]:
# Your code here

### Q15. [Intermediate] Merge batting and bowling DataFrames with indicator=True to see which players have both

In [168]:
# Hint: pd.merge(..., indicator=True)

### Q16. [Intermediate] Concatenate top10 and bottom10 but ignore the original index with ignore_index=True

In [169]:
# Your code here

### Q17. [Intermediate] Create a self-join to find pairs of players from the same team

In [170]:
# Hint: merge df with itself on 'Team'

### Q18. [Intermediate] Merge with validate='m:1' to ensure Team is unique in team_info

In [171]:
# Your code here

### Q19. [Advanced] Use join() on index to combine two DataFrames that share the same index

In [172]:
# Your code here

### Q20. [Advanced] Merge and then compute a new stat: Runs per Title (player runs / team titles)

In [173]:
# Your code here

### Q21. [Advanced] Use pd.concat with keys to create a hierarchical index for top10 and bottom10

In [174]:
# Hint: pd.concat([top10, bottom10], keys=['top', 'bottom'])

### Q22. [Advanced] Create a cross join (cartesian product) between top 5 players and all teams

In [175]:
# Hint: pd.merge with how='cross'

### Q23. [Advanced] Merge on multiple keys: Player name and Team both must match

In [176]:
# Your code here

### Q24. [Advanced] After merging batting + bowling + team_info, build a complete player scorecard DataFrame

In [177]:
# Your code here

### Q25. [Advanced] Use combine_first() to fill missing values in df from another DataFrame

In [178]:
# Your code here

---
# 📐 Section 8: Reshaping Data (25 Questions)
---

### Q1. [Basic] Transpose the first 5 rows of the DataFrame

In [179]:
# Your code here

### Q2. [Basic] Set 'Player' as the index of the DataFrame

In [180]:
# Your code here

### Q3. [Basic] Reset the index back to default numeric index

In [181]:
# Your code here

### Q4. [Basic] Create a pivot table: index=Team, values=Runs, aggfunc=sum

In [182]:
df['Team'] = df['Player'].str.split().str[-1]
# Your code here

### Q5. [Basic] Create a wide DataFrame with top 5 players and their Runs, SR, Avg columns, then melt it to long format

In [183]:
wide_df = df[['Player', 'Runs', 'SR', 'Avg']].head(5)
# Melt here

### Q6. [Basic] Sort the DataFrame by Runs descending and reset index

In [184]:
# Your code here

### Q7. [Basic] Sort by Team ascending and then by Runs descending

In [185]:
# Your code here

### Q8. [Basic] Use stack() on the top 5 rows to collapse columns into rows

In [186]:
# Your code here

### Q9. [Basic] Use unstack() to convert back from stacked format

In [187]:
# Your code here

### Q10. [Basic] Reverse the order of rows in the DataFrame

In [188]:
# Your code here

### Q11. [Intermediate] Melt the DataFrame to have: Player, stat_name, stat_value for Runs, SR, Avg, 4s, 6s

In [189]:
# Hint: pd.melt(df, id_vars=['Player'], value_vars=[...])

### Q12. [Intermediate] Create a pivot showing top 5 player names as columns, stats as rows

In [190]:
# Your code here

### Q13. [Intermediate] Use pivot_table with multiple aggfuncs (mean and max) for Runs per Team

In [191]:
# Your code here

### Q14. [Intermediate] Create a wide-format table: rows=Team, columns=century_scorer (Yes/No), values=count of players

In [192]:
df['Century_Scorer'] = df['100'].apply(lambda x: 'Yes' if x > 0 else 'No')
# Your pivot_table here

### Q15. [Intermediate] Use crosstab to show Team vs Performance_Label frequency

In [193]:
df['Performance'] = pd.cut(df['Runs'], bins=[0,100,300,1000], labels=['Low','Mid','High'])
# pd.crosstab here

### Q16. [Intermediate] After melt, filter only rows where stat_name = 'Runs'

In [194]:
# Your code here

### Q17. [Intermediate] Use pd.wide_to_long() on stats columns

In [195]:
# Your code here

### Q18. [Intermediate] Sort by multiple columns: Team asc, Runs desc, SR desc

In [196]:
# Your code here

### Q19. [Advanced] Create a multi-index DataFrame with (Team, Player) as index

In [197]:
# Your code here

### Q20. [Advanced] Unstack a multi-index DataFrame to bring one level to columns

In [198]:
# Your code here

### Q21. [Advanced] Use melt then pivot_table to go from wide → long → wide again (round-trip)

In [199]:
# Your code here

### Q22. [Advanced] Create a cross-tabulation with normalize='index' to show row percentages

In [200]:
# Your code here

### Q23. [Advanced] Explode a list-like column (create a 'Scores' column with lists and then explode it)

In [201]:
df_explode = df.head(5).copy()
df_explode['Scores'] = [[50, 45, 30], [80, 20], [60, 100, 40], [75], [55, 85, 90]]
# Explode here

### Q24. [Advanced] Convert the DataFrame from row-per-player to row-per-team format using groupby + pivot

In [202]:
# Your code here

### Q25. [Advanced] Use stack() and unstack() to reshape a multi-level pivot table

In [203]:
# Your code here

---
# 🧮 Section 9: Math & Statistics (25 Questions)
---

### Q1. [Basic] Calculate mean, median, and mode of the Runs column

In [204]:
# Your code here

### Q2. [Basic] Calculate the standard deviation of Strike Rate (SR)

In [205]:
# Your code here

### Q3. [Basic] Calculate variance of batting average (Avg)

In [206]:
# Your code here

### Q4. [Basic] Get the correlation matrix for numerical columns

In [207]:
# Your code here

### Q5. [Basic] Find correlation between Runs and 6s

In [208]:
# Your code here

### Q6. [Basic] Calculate cumulative sum of Runs (sorted by POS)

In [209]:
# Your code here

### Q7. [Basic] Calculate percentage change in Runs from player to player (by POS)

In [210]:
# Hint: df.sort_values('POS')['Runs'].pct_change()

### Q8. [Basic] Calculate the absolute values of the difference between Runs and mean Runs

In [211]:
# Your code here

### Q9. [Basic] Rank the players by Runs (1=highest)

In [212]:
# Your code here

### Q10. [Basic] Get the covariance matrix for Runs, SR, and Avg

In [213]:
# Your code here

### Q11. [Intermediate] Calculate the rolling 5-player average of Runs (sorted by POS)

In [214]:
# Your code here

### Q12. [Intermediate] Find the difference (diff) in Runs between consecutive players by POS

In [215]:
# Your code here

### Q13. [Intermediate] Calculate the expanding (cumulative) mean of SR as we go through POS order

In [216]:
# Your code here

### Q14. [Intermediate] Find which two columns have the highest positive correlation

In [217]:
# Your code here

### Q15. [Intermediate] Calculate the Spearman rank correlation between Runs and SR

In [218]:
# Hint: df[['Runs','SR']].corr(method='spearman')

### Q16. [Intermediate] Find the z-score of each player's Runs and identify those beyond 2 standard deviations

In [219]:
# Your code here

### Q17. [Intermediate] Calculate the MAD (Mean Absolute Deviation) of Runs column

In [220]:
# Hint: (df['Runs'] - df['Runs'].mean()).abs().mean()

### Q18. [Intermediate] Compute rolling standard deviation with window=10 for Runs

In [221]:
# Your code here

### Q19. [Advanced] Calculate the weighted average of Runs, weighted by number of innings (Inns)

In [222]:
# Hint: np.average(df['Runs'], weights=df['Inns'])

### Q20. [Advanced] Create a correlation heatmap data (correlation matrix rounded to 2 decimals)

In [223]:
# Your code here

### Q21. [Advanced] Calculate EWMA (Exponentially Weighted Moving Average) of Runs with span=5

In [224]:
# Hint: df['Runs'].ewm(span=5).mean()

### Q22. [Advanced] Find the percentile rank of each player's Runs within their team

In [225]:
# Hint: use groupby + transform with lambda and scipy.percentileofscore or rank

### Q23. [Advanced] Compute Pearson, Spearman, and Kendall correlation between Runs and Avg, compare them

In [226]:
# Your code here

### Q24. [Advanced] Calculate the information value (IV) proxy: how much does SR explain Runs category?

In [227]:
# Simplified: cross-tab Runs category vs SR quartile and see distribution

### Q25. [Advanced] Build a statistical summary table: for each team, show mean, std, skewness, and kurtosis of Runs

In [228]:
# Your code here

---
# 🔢 Section 10: Sorting & Ranking (25 Questions)
---

### Q1. [Basic] Sort players by Runs in descending order

In [229]:
# Your code here

### Q2. [Basic] Sort by Strike Rate (SR) ascending

In [230]:
# Your code here

### Q3. [Basic] Find top 5 players by Runs using nlargest()

In [231]:
# Your code here

### Q4. [Basic] Find bottom 5 players by Runs using nsmallest()

In [232]:
# Your code here

### Q5. [Basic] Sort by Player name alphabetically

In [233]:
# Your code here

### Q6. [Basic] Rank players by Runs (rank 1 = most runs)

In [234]:
# Hint: df['Runs'].rank(ascending=False)

### Q7. [Basic] Sort by 6s descending and show top 10

In [235]:
# Your code here

### Q8. [Basic] Find the player with the 3rd highest Strike Rate

In [236]:
# Your code here

### Q9. [Basic] Sort by Avg but put NaN values first

In [237]:
# Hint: na_position='first'

### Q10. [Basic] Sort by index (reset first if needed)

In [238]:
# Your code here

### Q11. [Intermediate] Sort by Team (asc), then by Runs (desc) within each team

In [239]:
df['Team'] = df['Player'].str.split().str[-1]
# Your code here

### Q12. [Intermediate] Rank players within each team by Runs (1 = top scorer in their team)

In [240]:
# Hint: df.groupby('Team')['Runs'].rank(ascending=False)

### Q13. [Intermediate] Find the top 3 players in each team by Runs

In [241]:
# Your code here

### Q14. [Intermediate] Use rank() with method='dense' on Runs column

In [242]:
# Your code here

### Q15. [Intermediate] Find the top 5 players by total boundaries (4s + 6s)

In [243]:
# Your code here

### Q16. [Intermediate] Sort by a custom key: length of player name

In [244]:
# Hint: df.sort_values('Player', key=lambda x: x.str.len())

### Q17. [Intermediate] Find the bottom 3 players in each team by SR

In [245]:
# Your code here

### Q18. [Intermediate] Use nlargest() to find top 10 players by Avg with at least 5 innings

In [246]:
# Your code here

### Q19. [Advanced] Create an overall batting score = 0.4*Runs + 0.3*SR + 0.3*Avg, then rank players

In [247]:
# Normalize first, then create score

### Q20. [Advanced] Rank by Runs but handle ties using 'min' method (all tied players get same rank)

In [248]:
# Your code here

### Q21. [Advanced] Sort by Runs descending and assign medal categories: Gold(top 3), Silver(4-10), Bronze(11-20)

In [249]:
# Your code here

### Q22. [Advanced] Find players who improved rank (lower POS number means better) compared to their Runs rank

In [250]:
# Runs_rank vs POS comparison

### Q23. [Advanced] Sort by multiple criteria with different ascending/descending for each

In [251]:
# Sort: Runs desc, SR desc, Avg desc, Mat asc

### Q24. [Advanced] For each team, find the player ranked #1 AND also ranked in overall top 20

In [252]:
# Your code here

### Q25. [Advanced] Build a leaderboard DataFrame: Overall_Rank, Team_Rank, Runs_Rank, SR_Rank for each player

In [253]:
# Your code here

---
# ⚙️ Section 11: Preparing Data for ML Models (25 Questions)
---

### Q1. [Basic] Remove the 'Player' column from the DataFrame (it's not numeric for ML)

In [254]:
df_ml = df.copy()
# Your code here

### Q2. [Basic] Check for and remove duplicate rows

In [255]:
# Your code here

### Q3. [Basic] Convert the DataFrame to a NumPy array for use with sklearn

In [256]:
# Your code here

### Q4. [Basic] Separate features (X) and target (y): target = Runs, features = everything else

In [257]:
# Your code here

### Q5. [Basic] Check if any column has constant values (all same value) - useless for ML

In [258]:
# Hint: df.nunique()

### Q6. [Basic] Create a 80/20 train-test split manually using sample()

In [259]:
train = df.sample(frac=0.8, random_state=42)
test = df.drop(train.index)
print(f'Train: {len(train)}, Test: {len(test)}')

Train: 134, Test: 33

### Q7. [Basic] Convert the HS column to numeric (remove '*' and cast to int)

In [260]:
# Your code here

### Q8. [Basic] Strip whitespace from the Player column using str.strip()

In [261]:
# Your code here

### Q9. [Basic] Convert all column names to lowercase

In [262]:
# Your code here

### Q10. [Basic] Extract all numeric columns into a new DataFrame

In [263]:
# Hint: df.select_dtypes(include=[np.number])

### Q11. [Intermediate] Extract date-like features from a hypothetical 'DOB' column (create one first)

In [264]:
df['DOB'] = pd.to_datetime(['1988-11-05'] * len(df))  # Simulated
# Extract year, month, day

### Q12. [Intermediate] One-hot encode Team column and drop original, then show final ML-ready features

In [265]:
# Your code here

### Q13. [Intermediate] Create a correlation filter: drop features correlated > 0.9 with another feature

In [266]:
# Your code here

### Q14. [Intermediate] Normalize all numeric columns using Min-Max scaling

In [267]:
# Your code here

### Q15. [Intermediate] Standardize (Z-score) all numeric columns

In [268]:
# Your code here

### Q16. [Intermediate] Create a feature importance proxy: correlation of each feature with Runs (target)

In [269]:
# Your code here

### Q17. [Intermediate] Handle outliers by clipping at 1st and 99th percentile for all numeric columns

In [270]:
# Your code here

### Q18. [Intermediate] Create target buckets for classification: Low/Medium/High runs scorer

In [271]:
# Your code here

### Q19. [Advanced] Create a full feature engineering pipeline function that takes raw df and returns ML-ready df

In [272]:
def prepare_for_ml(df):
    df = df.copy()
    # 1. Extract Team
    # 2. Remove Player column
    # 3. Clean HS column
    # 4. One-hot encode Team
    # 5. Fill nulls
    # 6. Normalize numeric columns
    return df

df_ready = prepare_for_ml(df)
df_ready.head()

,POS,Player,Runs,Mat,Inns,NO,HS,Avg,BF,SR,...,Run_per_Match,Has_century,City,Runs_Category,Dismissal_Rate,Performance_Label,Has_Century,Century_Scorer,Performance,DOB
0,1,Virat Kohli RCB,741,15,15,3,113,61.75,479,154.69,...,49.400000,1,Bangalore,Q4,0.800000,None,1,Yes,High,1988-11-05
1,2,Ruturaj Gaikwad CSK,583,14,14,3,108,53.00,413,141.16,...,41.642857,1,Chennai,Q4,0.785714,None,1,Yes,High,1988-11-05
2,3,Riyan Parag RR,573,16,14,3,84,52.09,384,149.21,...,35.812500,1,Jaipur,Q4,0.785714,None,0,No,High,1988-11-05
3,4,Travis Head SRH,567,15,15,1,102,40.50,296,191.55,...,37.800000,1,Hyderabad,Q4,0.933333,None,1,Yes,High,1988-11-05
4,5,Sanju Samson RR,531,16,15,4,86,48.27,346,153.46,...,33.187500,1,Jaipur,Q4,0.733333,None,0,No,High,1988-11-05

### Q20. [Advanced] Use pd.get_dummies + train/test split ensuring same columns in both sets

In [273]:
# Your code here

### Q21. [Advanced] Create binary target: 'Good_Batsman' = 1 if Runs > median AND SR > mean, else 0

In [274]:
# Your code here

### Q22. [Advanced] Remove features with low variance (std < 1) as they add noise to ML models

In [275]:
# Your code here

### Q23. [Advanced] Create interaction features between all pairs of numeric columns automatically

In [276]:
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
# Create pairwise products

### Q24. [Advanced] Perform stratified sampling by Team (same proportion from each team in train/test)

In [277]:
# Hint: groupby Team, sample from each group

### Q25. [Advanced] Build the final complete ML dataset: 10+ features, encoded, normalized, train/test split, print shapes

In [278]:
# Complete pipeline
df_final = df.copy()

# Feature engineering
# Encoding
# Normalization
# Train/test split

# Print final shapes and feature names

---
# 🏆 Congratulations!

You have completed all **275 Pandas practice questions** across 11 sections using the IPL 2024 dataset!

## Summary
| Section | Topic | Questions |
|---|---|---|
| 1 | Data Loading & Saving | 25 |
| 2 | Exploratory Data Analysis | 25 |
| 3 | Handling Missing Values | 25 |
| 4 | Selecting & Filtering | 25 |
| 5 | Feature Engineering | 25 |
| 6 | Aggregation & GroupBy | 25 |
| 7 | Merging & Joining | 25 |
| 8 | Reshaping Data | 25 |
| 9 | Math & Statistics | 25 |
| 10 | Sorting & Ranking | 25 |
| 11 | ML Data Preparation | 25 |
| **Total** | | **275** |

### 🎯 Next Steps:
1. Try building a regression model to predict player Runs
2. Try a classification model to predict if a player will score 100+
3. Explore Seaborn/Matplotlib to visualize the stats
---